var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(m){var p=0;return function(){return p<m.length?{done:!1,value:m[p++]}:{done:!0}}};$jscomp.arrayIterator=function(m){return{next:$jscomp.arrayIteratorImpl(m)}};$jscomp.makeIterator=function(m){var p="undefined"!=typeof Symbol&&Symbol.iterator&&m[Symbol.iterator];return p?p.call(m):$jscomp.arrayIterator(m)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.getGlobal=function(m){m=["object"==typeof globalThis&&globalThis,m,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var p=0;p<m.length;++p){var k=m[p];if(k&&k.Math==Math)return k}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(m,p,k){if(m==Array.prototype||m==Object.prototype)return m;m[p]=k.value;return m};$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";
var $jscomp$lookupPolyfilledValue=function(m,p){var k=$jscomp.propertyToPolyfillSymbol[p];if(null==k)return m[p];k=m[k];return void 0!==k?k:m[p]};$jscomp.polyfill=function(m,p,k,r){p&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(m,p,k,r):$jscomp.polyfillUnisolated(m,p,k,r))};
$jscomp.polyfillUnisolated=function(m,p,k,r){k=$jscomp.global;m=m.split(".");for(r=0;r<m.length-1;r++){var l=m[r];if(!(l in k))return;k=k[l]}m=m[m.length-1];r=k[m];p=p(r);p!=r&&null!=p&&$jscomp.defineProperty(k,m,{configurable:!0,writable:!0,value:p})};
$jscomp.polyfillIsolated=function(m,p,k,r){var l=m.split(".");m=1===l.length;r=l[0];r=!m&&r in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var B=0;B<l.length-1;B++){var h=l[B];if(!(h in r))return;r=r[h]}l=l[l.length-1];k=$jscomp.IS_SYMBOL_NATIVE&&"es6"===k?r[l]:null;p=p(k);null!=p&&(m?$jscomp.defineProperty($jscomp.polyfills,l,{configurable:!0,writable:!0,value:p}):p!==k&&(void 0===$jscomp.propertyToPolyfillSymbol[l]&&(k=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[l]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(l):$jscomp.POLYFILL_PREFIX+k+"$"+l),$jscomp.defineProperty(r,$jscomp.propertyToPolyfillSymbol[l],{configurable:!0,writable:!0,value:p})))};
$jscomp.polyfill("Promise",function(m){function p(){this.batch_=null}function k(h){return h instanceof l?h:new l(function(q,v){q(h)})}if(m&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return m;p.prototype.asyncExecute=function(h){if(null==this.batch_){this.batch_=[];var q=this;this.asyncExecuteFunction(function(){q.executeBatch_()})}this.batch_.push(h)};
var r=$jscomp.global.setTimeout;p.prototype.asyncExecuteFunction=function(h){r(h,0)};p.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var h=this.batch_;this.batch_=[];for(var q=0;q<h.length;++q){var v=h[q];h[q]=null;try{v()}catch(C){this.asyncThrow_(C)}}}this.batch_=null};p.prototype.asyncThrow_=function(h){this.asyncExecuteFunction(function(){throw h;})};var l=function(h){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var q=this.createResolveAndReject_();
try{h(q.resolve,q.reject)}catch(v){q.reject(v)}};l.prototype.createResolveAndReject_=function(){function h(C){return function(I){v||(v=!0,C.call(q,I))}}var q=this,v=!1;return{resolve:h(this.resolveTo_),reject:h(this.reject_)}};l.prototype.resolveTo_=function(h){if(h===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(h instanceof l)this.settleSameAsPromise_(h);else{a:switch(typeof h){case "object":var q=null!=h;break a;case "function":q=!0;break a;default:q=!1}q?this.resolveToNonPromiseObj_(h):
this.fulfill_(h)}};l.prototype.resolveToNonPromiseObj_=function(h){var q=void 0;try{q=h.then}catch(v){this.reject_(v);return}"function"==typeof q?this.settleSameAsThenable_(q,h):this.fulfill_(h)};l.prototype.reject_=function(h){this.settle_(2,h)};l.prototype.fulfill_=function(h){this.settle_(1,h)};l.prototype.settle_=function(h,q){if(0!=this.state_)throw Error("Cannot settle("+h+", "+q+"): Promise already settled in state"+this.state_);this.state_=h;this.result_=q;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};l.prototype.scheduleUnhandledRejectionCheck_=function(){var h=this;r(function(){if(h.notifyUnhandledRejection_()){var q=$jscomp.global.console;"undefined"!==typeof q&&q.error(h.result_)}},1)};l.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var h=$jscomp.global.CustomEvent,q=$jscomp.global.Event,v=$jscomp.global.dispatchEvent;if("undefined"===typeof v)return!0;"function"===typeof h?h=new h("unhandledrejection",{cancelable:!0}):
"function"===typeof q?h=new q("unhandledrejection",{cancelable:!0}):(h=$jscomp.global.document.createEvent("CustomEvent"),h.initCustomEvent("unhandledrejection",!1,!0,h));h.promise=this;h.reason=this.result_;return v(h)};l.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var h=0;h<this.onSettledCallbacks_.length;++h)B.asyncExecute(this.onSettledCallbacks_[h]);this.onSettledCallbacks_=null}};var B=new p;l.prototype.settleSameAsPromise_=function(h){var q=this.createResolveAndReject_();
h.callWhenSettled_(q.resolve,q.reject)};l.prototype.settleSameAsThenable_=function(h,q){var v=this.createResolveAndReject_();try{h.call(q,v.resolve,v.reject)}catch(C){v.reject(C)}};l.prototype.then=function(h,q){function v(w,D){return"function"==typeof w?function(S){try{C(w(S))}catch(O){I(O)}}:D}var C,I,T=new l(function(w,D){C=w;I=D});this.callWhenSettled_(v(h,C),v(q,I));return T};l.prototype.catch=function(h){return this.then(void 0,h)};l.prototype.callWhenSettled_=function(h,q){function v(){switch(C.state_){case 1:h(C.result_);
break;case 2:q(C.result_);break;default:throw Error("Unexpected state: "+C.state_);}}var C=this;null==this.onSettledCallbacks_?B.asyncExecute(v):this.onSettledCallbacks_.push(v);this.isRejectionHandled_=!0};l.resolve=k;l.reject=function(h){return new l(function(q,v){v(h)})};l.race=function(h){return new l(function(q,v){for(var C=$jscomp.makeIterator(h),I=C.next();!I.done;I=C.next())k(I.value).callWhenSettled_(q,v)})};l.all=function(h){var q=$jscomp.makeIterator(h),v=q.next();return v.done?k([]):new l(function(C,
I){function T(S){return function(O){w[S]=O;D--;0==D&&C(w)}}var w=[],D=0;do w.push(void 0),D++,k(v.value).callWhenSettled_(T(w.length-1),I),v=q.next();while(!v.done)})};return l},"es6","es3");$jscomp.checkStringArgs=function(m,p,k){if(null==m)throw new TypeError("The 'this' value for String.prototype."+k+" must not be null or undefined");if(p instanceof RegExp)throw new TypeError("First argument to String.prototype."+k+" must not be a regular expression");return m+""};
$jscomp.polyfill("String.prototype.startsWith",function(m){return m?m:function(p,k){var r=$jscomp.checkStringArgs(this,p,"startsWith");p+="";var l=r.length,B=p.length;k=Math.max(0,Math.min(k|0,r.length));for(var h=0;h<B&&k<l;)if(r[k++]!=p[h++])return!1;return h>=B}},"es6","es3");
$jscomp.polyfill("Array.prototype.copyWithin",function(m){function p(k){k=Number(k);return Infinity===k||-Infinity===k?k:k|0}return m?m:function(k,r,l){var B=this.length;k=p(k);r=p(r);l=void 0===l?B:p(l);k=0>k?Math.max(B+k,0):Math.min(k,B);r=0>r?Math.max(B+r,0):Math.min(r,B);l=0>l?Math.max(B+l,0):Math.min(l,B);if(k<r)for(;r<l;)r in this?this[k++]=this[r++]:(delete this[k++],r++);else for(l=Math.min(l,B+r-k),k+=l-r;l>r;)--l in this?this[--k]=this[l]:delete this[--k];return this}},"es6","es3");
$jscomp.typedArrayCopyWithin=function(m){return m?m:Array.prototype.copyWithin};$jscomp.polyfill("Int8Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Uint8Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Uint8ClampedArray.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Int16Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");
$jscomp.polyfill("Uint16Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Int32Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Uint32Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Float32Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Float64Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");
var DracoEncoderModule=function(){var m="undefined"!==typeof document&&document.currentScript?document.currentScript.src:void 0;"undefined"!==typeof __filename&&(m=m||__filename);return function(p){function k(f){return a.locateFile?a.locateFile(f,L):L+f}function r(f,b){f||B("Assertion failed: "+b)}function l(f){sa=f;a.HEAP8=P=new Int8Array(f);a.HEAP16=ka=new Int16Array(f);a.HEAP32=K=new Int32Array(f);a.HEAPU8=la=new Uint8Array(f);a.HEAPU16=new Uint16Array(f);a.HEAPU32=new Uint32Array(f);a.HEAPF32=
ma=new Float32Array(f);a.HEAPF64=new Float64Array(f)}function B(f){if(a.onAbort)a.onAbort(f);f="Aborted("+f+")";Y(f);ta=!0;f=new WebAssembly.RuntimeError(f+". Build with -s ASSERTIONS=1 for more info.");na(f);throw f;}function h(f){try{if(f==J&&Z)return new Uint8Array(Z);if(oa)return oa(f);throw"both async and sync fetching of the wasm failed";}catch(b){B(b)}}function q(){if(!Z&&(ua||aa)){if("function"===typeof fetch&&!J.startsWith("file://"))return fetch(J,{credentials:"same-origin"}).then(function(f){if(!f.ok)throw"failed to load wasm binary file at '"+
J+"'";return f.arrayBuffer()}).catch(function(){return h(J)});if(pa)return new Promise(function(f,b){pa(J,function(c){f(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return h(J)})}function v(f){for(;0<f.length;){var b=f.shift();if("function"==typeof b)b(a);else{var c=b.func;"number"===typeof c?void 0===b.arg?C(c)():C(c)(b.arg):c(void 0===b.arg?null:b.arg)}}}function C(f){var b=ea[f];b||(f>=ea.length&&(ea.length=f+1),ea[f]=b=va.get(f));return b}function I(f){this.excPtr=f;this.ptr=
f-16;this.set_type=function(b){K[this.ptr+4>>2]=b};this.get_type=function(){return K[this.ptr+4>>2]};this.set_destructor=function(b){K[this.ptr+8>>2]=b};this.get_destructor=function(){return K[this.ptr+8>>2]};this.set_refcount=function(b){K[this.ptr>>2]=b};this.set_caught=function(b){P[this.ptr+12>>0]=b?1:0};this.get_caught=function(){return 0!=P[this.ptr+12>>0]};this.set_rethrown=function(b){P[this.ptr+13>>0]=b?1:0};this.get_rethrown=function(){return 0!=P[this.ptr+13>>0]};this.init=function(b,c){this.set_type(b);
this.set_destructor(c);this.set_refcount(0);this.set_caught(!1);this.set_rethrown(!1)};this.add_ref=function(){K[this.ptr>>2]+=1};this.release_ref=function(){var b=K[this.ptr>>2];K[this.ptr>>2]=b-1;return 1===b}}function T(f){function b(){if(!fa&&(fa=!0,a.calledRun=!0,!ta)){wa=!0;v(qa);xa(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;)ya.unshift(a.postRun.shift());v(ya)}}if(!(0<U)){if(a.preRun)for("function"==
typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)za.unshift(a.preRun.shift());v(za);0<U||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}function w(){}function D(f){return(f||w).__cache__}function S(f,b){var c=D(b),d=c[f];if(d)return d;d=Object.create((b||w).prototype);d.ptr=f;return c[f]=d}function O(f){if("string"===typeof f){for(var b=0,c=0;c<f.length;++c){var d=f.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<
10)|f.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}b=Array(b+1);c=0;d=b.length;if(0<d){d=c+d-1;for(var e=0;e<f.length;++e){var g=f.charCodeAt(e);if(55296<=g&&57343>=g){var t=f.charCodeAt(++e);g=65536+((g&1023)<<10)|t&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0}f=n.alloc(b,P);n.copy(b,P,
f);return f}return f}function ha(f){if("object"===typeof f){var b=n.alloc(f,P);n.copy(f,P,b);return b}return f}function ia(f){if("object"===typeof f){var b=n.alloc(f,ka);n.copy(f,ka,b);return b}return f}function V(f){if("object"===typeof f){var b=n.alloc(f,K);n.copy(f,K,b);return b}return f}function ba(f){if("object"===typeof f){var b=n.alloc(f,ma);n.copy(f,ma,b);return b}return f}function Q(){throw"cannot construct a VoidPtr, no constructor in IDL";}function M(){this.ptr=Aa();D(M)[this.ptr]=this}
function z(){this.ptr=Ba();D(z)[this.ptr]=this}function G(){this.ptr=Ca();D(G)[this.ptr]=this}function E(){this.ptr=Da();D(E)[this.ptr]=this}function N(){this.ptr=Ea();D(N)[this.ptr]=this}function H(){this.ptr=Fa();D(H)[this.ptr]=this}function F(){this.ptr=Ga();D(F)[this.ptr]=this}function x(){this.ptr=Ha();D(x)[this.ptr]=this}function u(){this.ptr=Ia();D(u)[this.ptr]=this}function y(){this.ptr=Ja();D(y)[this.ptr]=this}function A(f){f&&"object"===typeof f&&(f=f.ptr);this.ptr=Ka(f);D(A)[this.ptr]=
this}p=p||{};var a="undefined"!==typeof p?p:{},xa,na;a.ready=new Promise(function(f,b){xa=f;na=b});var La=!1,Ma=!1;a.onRuntimeInitialized=function(){La=!0;if(Ma&&"function"===typeof a.onModuleLoaded)a.onModuleLoaded(a)};a.onModuleParsed=function(){Ma=!0;if(La&&"function"===typeof a.onModuleLoaded)a.onModuleLoaded(a)};a.isVersionSupported=function(f){if("string"!==typeof f)return!1;f=f.split(".");return 2>f.length||3<f.length?!1:1==f[0]&&0<=f[1]&&5>=f[1]?!0:0!=f[0]||10<f[1]?!1:!0};var ca={},R;for(R in a)a.hasOwnProperty(R)&&
(ca[R]=a[R]);var ua="object"===typeof window,aa="function"===typeof importScripts,L="",W,X;if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node){L=aa?require("path").dirname(L)+"/":__dirname+"/";var Na=function(f,b){W||(W=require("fs"));X||(X=require("path"));f=X.normalize(f);return W.readFileSync(f,b?null:"utf8")};var oa=function(f){f=Na(f,!0);f.buffer||(f=new Uint8Array(f));r(f.buffer);return f};var pa=function(f,b,c){W||(W=require("fs"));X||
(X=require("path"));f=X.normalize(f);W.readFile(f,function(d,e){d?c(d):b(e.buffer)})};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);a.inspect=function(){return"[Emscripten Module object]"}}else if(ua||aa)aa?L=self.location.href:"undefined"!==typeof document&&document.currentScript&&(L=document.currentScript.src),m&&(L=m),L=0!==L.indexOf("blob:")?L.substr(0,L.replace(/[?#].*/,"").lastIndexOf("/")+1):"",Na=function(f){var b=new XMLHttpRequest;b.open("GET",f,!1);b.send(null);
return b.responseText},aa&&(oa=function(f){var b=new XMLHttpRequest;b.open("GET",f,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),pa=function(f,b,c){var d=new XMLHttpRequest;d.open("GET",f,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};a.print||console.log.bind(console);var Y=a.printErr||console.warn.bind(console);for(R in ca)ca.hasOwnProperty(R)&&(a[R]=ca[R]);ca=null;var Z;
a.wasmBinary&&(Z=a.wasmBinary);"object"!==typeof WebAssembly&&B("no native wasm support detected");var ja,ta=!1,sa,P,la,ka,K,ma,va,za=[],qa=[],ya=[],wa=!1,U=0,ra=null,da=null;a.preloadedImages={};a.preloadedAudios={};var J="draco_encoder.wasm";J.startsWith("data:application/octet-stream;base64,")||(J=k(J));var ea=[],rc=0,sc={e:function(f){return Oa(f+16)+16},d:function(f,b,c){(new I(f)).init(b,c);rc++;throw f;},a:function(){B("")},b:function(f,b,c){la.copyWithin(f,b,b+c)},c:function(f){var b=la.length;
f>>>=0;if(2147483648<f)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,f+100663296);var e=Math,g=e.min;d=Math.max(f,d);0<d%65536&&(d+=65536-d%65536);e=g.call(e,2147483648,d);a:{try{ja.grow(e-sa.byteLength+65535>>>16);l(ja.buffer);var t=1;break a}catch(tc){}t=void 0}if(t)return!0}return!1}};(function(){function f(e,g){a.asm=e.exports;ja=a.asm.f;l(ja.buffer);va=a.asm.h;qa.unshift(a.asm.g);U--;a.monitorRunDependencies&&a.monitorRunDependencies(U);0==U&&(null!==ra&&(clearInterval(ra),ra=
null),da&&(e=da,da=null,e()))}function b(e){f(e.instance)}function c(e){return q().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(e,function(g){Y("failed to asynchronously prepare wasm: "+g);B(g)})}var d={a:sc};U++;a.monitorRunDependencies&&a.monitorRunDependencies(U);if(a.instantiateWasm)try{return a.instantiateWasm(d,f)}catch(e){return Y("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return Z||"function"!==typeof WebAssembly.instantiateStreaming||
J.startsWith("data:application/octet-stream;base64,")||J.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(J,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){Y("wasm streaming compile failed: "+g);Y("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(na);return{}})();a.___wasm_call_ctors=function(){return(a.___wasm_call_ctors=a.asm.g).apply(null,arguments)};var Pa=a._emscripten_bind_VoidPtr___destroy___0=function(){return(Pa=
a._emscripten_bind_VoidPtr___destroy___0=a.asm.i).apply(null,arguments)},Aa=a._emscripten_bind_GeometryAttribute_GeometryAttribute_0=function(){return(Aa=a._emscripten_bind_GeometryAttribute_GeometryAttribute_0=a.asm.j).apply(null,arguments)},Qa=a._emscripten_bind_GeometryAttribute___destroy___0=function(){return(Qa=a._emscripten_bind_GeometryAttribute___destroy___0=a.asm.k).apply(null,arguments)},Ba=a._emscripten_bind_PointAttribute_PointAttribute_0=function(){return(Ba=a._emscripten_bind_PointAttribute_PointAttribute_0=
a.asm.l).apply(null,arguments)},Ra=a._emscripten_bind_PointAttribute_size_0=function(){return(Ra=a._emscripten_bind_PointAttribute_size_0=a.asm.m).apply(null,arguments)},Sa=a._emscripten_bind_PointAttribute_attribute_type_0=function(){return(Sa=a._emscripten_bind_PointAttribute_attribute_type_0=a.asm.n).apply(null,arguments)},Ta=a._emscripten_bind_PointAttribute_data_type_0=function(){return(Ta=a._emscripten_bind_PointAttribute_data_type_0=a.asm.o).apply(null,arguments)},Ua=a._emscripten_bind_PointAttribute_num_components_0=
function(){return(Ua=a._emscripten_bind_PointAttribute_num_components_0=a.asm.p).apply(null,arguments)},Va=a._emscripten_bind_PointAttribute_normalized_0=function(){return(Va=a._emscripten_bind_PointAttribute_normalized_0=a.asm.q).apply(null,arguments)},Wa=a._emscripten_bind_PointAttribute_byte_stride_0=function(){return(Wa=a._emscripten_bind_PointAttribute_byte_stride_0=a.asm.r).apply(null,arguments)},Xa=a._emscripten_bind_PointAttribute_byte_offset_0=function(){return(Xa=a._emscripten_bind_PointAttribute_byte_offset_0=
a.asm.s).apply(null,arguments)},Ya=a._emscripten_bind_PointAttribute_unique_id_0=function(){return(Ya=a._emscripten_bind_PointAttribute_unique_id_0=a.asm.t).apply(null,arguments)},Za=a._emscripten_bind_PointAttribute___destroy___0=function(){return(Za=a._emscripten_bind_PointAttribute___destroy___0=a.asm.u).apply(null,arguments)},Ca=a._emscripten_bind_PointCloud_PointCloud_0=function(){return(Ca=a._emscripten_bind_PointCloud_PointCloud_0=a.asm.v).apply(null,arguments)},$a=a._emscripten_bind_PointCloud_num_attributes_0=
function(){return($a=a._emscripten_bind_PointCloud_num_attributes_0=a.asm.w).apply(null,arguments)},ab=a._emscripten_bind_PointCloud_num_points_0=function(){return(ab=a._emscripten_bind_PointCloud_num_points_0=a.asm.x).apply(null,arguments)},bb=a._emscripten_bind_PointCloud___destroy___0=function(){return(bb=a._emscripten_bind_PointCloud___destroy___0=a.asm.y).apply(null,arguments)},Da=a._emscripten_bind_Mesh_Mesh_0=function(){return(Da=a._emscripten_bind_Mesh_Mesh_0=a.asm.z).apply(null,arguments)},
cb=a._emscripten_bind_Mesh_num_faces_0=function(){return(cb=a._emscripten_bind_Mesh_num_faces_0=a.asm.A).apply(null,arguments)},db=a._emscripten_bind_Mesh_num_attributes_0=function(){return(db=a._emscripten_bind_Mesh_num_attributes_0=a.asm.B).apply(null,arguments)},eb=a._emscripten_bind_Mesh_num_points_0=function(){return(eb=a._emscripten_bind_Mesh_num_points_0=a.asm.C).apply(null,arguments)},fb=a._emscripten_bind_Mesh_set_num_points_1=function(){return(fb=a._emscripten_bind_Mesh_set_num_points_1=
a.asm.D).apply(null,arguments)},gb=a._emscripten_bind_Mesh___destroy___0=function(){return(gb=a._emscripten_bind_Mesh___destroy___0=a.asm.E).apply(null,arguments)},Ea=a._emscripten_bind_Metadata_Metadata_0=function(){return(Ea=a._emscripten_bind_Metadata_Metadata_0=a.asm.F).apply(null,arguments)},hb=a._emscripten_bind_Metadata___destroy___0=function(){return(hb=a._emscripten_bind_Metadata___destroy___0=a.asm.G).apply(null,arguments)},Fa=a._emscripten_bind_DracoInt8Array_DracoInt8Array_0=function(){return(Fa=
a._emscripten_bind_DracoInt8Array_DracoInt8Array_0=a.asm.H).apply(null,arguments)},ib=a._emscripten_bind_DracoInt8Array_GetValue_1=function(){return(ib=a._emscripten_bind_DracoInt8Array_GetValue_1=a.asm.I).apply(null,arguments)},jb=a._emscripten_bind_DracoInt8Array_size_0=function(){return(jb=a._emscripten_bind_DracoInt8Array_size_0=a.asm.J).apply(null,arguments)},kb=a._emscripten_bind_DracoInt8Array___destroy___0=function(){return(kb=a._emscripten_bind_DracoInt8Array___destroy___0=a.asm.K).apply(null,
arguments)},Ga=a._emscripten_bind_MetadataBuilder_MetadataBuilder_0=function(){return(Ga=a._emscripten_bind_MetadataBuilder_MetadataBuilder_0=a.asm.L).apply(null,arguments)},lb=a._emscripten_bind_MetadataBuilder_AddStringEntry_3=function(){return(lb=a._emscripten_bind_MetadataBuilder_AddStringEntry_3=a.asm.M).apply(null,arguments)},mb=a._emscripten_bind_MetadataBuilder_AddIntEntry_3=function(){return(mb=a._emscripten_bind_MetadataBuilder_AddIntEntry_3=a.asm.N).apply(null,arguments)},nb=a._emscripten_bind_MetadataBuilder_AddIntEntryArray_4=
function(){return(nb=a._emscripten_bind_MetadataBuilder_AddIntEntryArray_4=a.asm.O).apply(null,arguments)},ob=a._emscripten_bind_MetadataBuilder_AddDoubleEntry_3=function(){return(ob=a._emscripten_bind_MetadataBuilder_AddDoubleEntry_3=a.asm.P).apply(null,arguments)},pb=a._emscripten_bind_MetadataBuilder___destroy___0=function(){return(pb=a._emscripten_bind_MetadataBuilder___destroy___0=a.asm.Q).apply(null,arguments)},Ha=a._emscripten_bind_PointCloudBuilder_PointCloudBuilder_0=function(){return(Ha=
a._emscripten_bind_PointCloudBuilder_PointCloudBuilder_0=a.asm.R).apply(null,arguments)},qb=a._emscripten_bind_PointCloudBuilder_AddFloatAttribute_5=function(){return(qb=a._emscripten_bind_PointCloudBuilder_AddFloatAttribute_5=a.asm.S).apply(null,arguments)},rb=a._emscripten_bind_PointCloudBuilder_AddInt8Attribute_5=function(){return(rb=a._emscripten_bind_PointCloudBuilder_AddInt8Attribute_5=a.asm.T).apply(null,arguments)},sb=a._emscripten_bind_PointCloudBuilder_AddUInt8Attribute_5=function(){return(sb=
a._emscripten_bind_PointCloudBuilder_AddUInt8Attribute_5=a.asm.U).apply(null,arguments)},tb=a._emscripten_bind_PointCloudBuilder_AddInt16Attribute_5=function(){return(tb=a._emscripten_bind_PointCloudBuilder_AddInt16Attribute_5=a.asm.V).apply(null,arguments)},ub=a._emscripten_bind_PointCloudBuilder_AddUInt16Attribute_5=function(){return(ub=a._emscripten_bind_PointCloudBuilder_AddUInt16Attribute_5=a.asm.W).apply(null,arguments)},vb=a._emscripten_bind_PointCloudBuilder_AddInt32Attribute_5=function(){return(vb=
a._emscripten_bind_PointCloudBuilder_AddInt32Attribute_5=a.asm.X).apply(null,arguments)},wb=a._emscripten_bind_PointCloudBuilder_AddUInt32Attribute_5=function(){return(wb=a._emscripten_bind_PointCloudBuilder_AddUInt32Attribute_5=a.asm.Y).apply(null,arguments)},xb=a._emscripten_bind_PointCloudBuilder_AddMetadata_2=function(){return(xb=a._emscripten_bind_PointCloudBuilder_AddMetadata_2=a.asm.Z).apply(null,arguments)},yb=a._emscripten_bind_PointCloudBuilder_SetMetadataForAttribute_3=function(){return(yb=
a._emscripten_bind_PointCloudBuilder_SetMetadataForAttribute_3=a.asm._).apply(null,arguments)},zb=a._emscripten_bind_PointCloudBuilder___destroy___0=function(){return(zb=a._emscripten_bind_PointCloudBuilder___destroy___0=a.asm.$).apply(null,arguments)},Ia=a._emscripten_bind_MeshBuilder_MeshBuilder_0=function(){return(Ia=a._emscripten_bind_MeshBuilder_MeshBuilder_0=a.asm.aa).apply(null,arguments)},Ab=a._emscripten_bind_MeshBuilder_AddFacesToMesh_3=function(){return(Ab=a._emscripten_bind_MeshBuilder_AddFacesToMesh_3=
a.asm.ba).apply(null,arguments)},Bb=a._emscripten_bind_MeshBuilder_AddFloatAttributeToMesh_5=function(){return(Bb=a._emscripten_bind_MeshBuilder_AddFloatAttributeToMesh_5=a.asm.ca).apply(null,arguments)},Cb=a._emscripten_bind_MeshBuilder_AddInt32AttributeToMesh_5=function(){return(Cb=a._emscripten_bind_MeshBuilder_AddInt32AttributeToMesh_5=a.asm.da).apply(null,arguments)},Db=a._emscripten_bind_MeshBuilder_AddMetadataToMesh_2=function(){return(Db=a._emscripten_bind_MeshBuilder_AddMetadataToMesh_2=
a.asm.ea).apply(null,arguments)},Eb=a._emscripten_bind_MeshBuilder_AddFloatAttribute_5=function(){return(Eb=a._emscripten_bind_MeshBuilder_AddFloatAttribute_5=a.asm.fa).apply(null,arguments)},Fb=a._emscripten_bind_MeshBuilder_AddInt8Attribute_5=function(){return(Fb=a._emscripten_bind_MeshBuilder_AddInt8Attribute_5=a.asm.ga).apply(null,arguments)},Gb=a._emscripten_bind_MeshBuilder_AddUInt8Attribute_5=function(){return(Gb=a._emscripten_bind_MeshBuilder_AddUInt8Attribute_5=a.asm.ha).apply(null,arguments)},
Hb=a._emscripten_bind_MeshBuilder_AddInt16Attribute_5=function(){return(Hb=a._emscripten_bind_MeshBuilder_AddInt16Attribute_5=a.asm.ia).apply(null,arguments)},Ib=a._emscripten_bind_MeshBuilder_AddUInt16Attribute_5=function(){return(Ib=a._emscripten_bind_MeshBuilder_AddUInt16Attribute_5=a.asm.ja).apply(null,arguments)},Jb=a._emscripten_bind_MeshBuilder_AddInt32Attribute_5=function(){return(Jb=a._emscripten_bind_MeshBuilder_AddInt32Attribute_5=a.asm.ka).apply(null,arguments)},Kb=a._emscripten_bind_MeshBuilder_AddUInt32Attribute_5=
function(){return(Kb=a._emscripten_bind_MeshBuilder_AddUInt32Attribute_5=a.asm.la).apply(null,arguments)},Lb=a._emscripten_bind_MeshBuilder_AddMetadata_2=function(){return(Lb=a._emscripten_bind_MeshBuilder_AddMetadata_2=a.asm.ma).apply(null,arguments)},Mb=a._emscripten_bind_MeshBuilder_SetMetadataForAttribute_3=function(){return(Mb=a._emscripten_bind_MeshBuilder_SetMetadataForAttribute_3=a.asm.na).apply(null,arguments)},Nb=a._emscripten_bind_MeshBuilder___destroy___0=function(){return(Nb=a._emscripten_bind_MeshBuilder___destroy___0=
a.asm.oa).apply(null,arguments)},Ja=a._emscripten_bind_Encoder_Encoder_0=function(){return(Ja=a._emscripten_bind_Encoder_Encoder_0=a.asm.pa).apply(null,arguments)},Ob=a._emscripten_bind_Encoder_SetEncodingMethod_1=function(){return(Ob=a._emscripten_bind_Encoder_SetEncodingMethod_1=a.asm.qa).apply(null,arguments)},Pb=a._emscripten_bind_Encoder_SetAttributeQuantization_2=function(){return(Pb=a._emscripten_bind_Encoder_SetAttributeQuantization_2=a.asm.ra).apply(null,arguments)},Qb=a._emscripten_bind_Encoder_SetAttributeExplicitQuantization_5=
function(){return(Qb=a._emscripten_bind_Encoder_SetAttributeExplicitQuantization_5=a.asm.sa).apply(null,arguments)},Rb=a._emscripten_bind_Encoder_SetSpeedOptions_2=function(){return(Rb=a._emscripten_bind_Encoder_SetSpeedOptions_2=a.asm.ta).apply(null,arguments)},Sb=a._emscripten_bind_Encoder_SetTrackEncodedProperties_1=function(){return(Sb=a._emscripten_bind_Encoder_SetTrackEncodedProperties_1=a.asm.ua).apply(null,arguments)},Tb=a._emscripten_bind_Encoder_EncodeMeshToDracoBuffer_2=function(){return(Tb=
a._emscripten_bind_Encoder_EncodeMeshToDracoBuffer_2=a.asm.va).apply(null,arguments)},Ub=a._emscripten_bind_Encoder_EncodePointCloudToDracoBuffer_3=function(){return(Ub=a._emscripten_bind_Encoder_EncodePointCloudToDracoBuffer_3=a.asm.wa).apply(null,arguments)},Vb=a._emscripten_bind_Encoder_GetNumberOfEncodedPoints_0=function(){return(Vb=a._emscripten_bind_Encoder_GetNumberOfEncodedPoints_0=a.asm.xa).apply(null,arguments)},Wb=a._emscripten_bind_Encoder_GetNumberOfEncodedFaces_0=function(){return(Wb=
a._emscripten_bind_Encoder_GetNumberOfEncodedFaces_0=a.asm.ya).apply(null,arguments)},Xb=a._emscripten_bind_Encoder___destroy___0=function(){return(Xb=a._emscripten_bind_Encoder___destroy___0=a.asm.za).apply(null,arguments)},Ka=a._emscripten_bind_ExpertEncoder_ExpertEncoder_1=function(){return(Ka=a._emscripten_bind_ExpertEncoder_ExpertEncoder_1=a.asm.Aa).apply(null,arguments)},Yb=a._emscripten_bind_ExpertEncoder_SetEncodingMethod_1=function(){return(Yb=a._emscripten_bind_ExpertEncoder_SetEncodingMethod_1=
a.asm.Ba).apply(null,arguments)},Zb=a._emscripten_bind_ExpertEncoder_SetAttributeQuantization_2=function(){return(Zb=a._emscripten_bind_ExpertEncoder_SetAttributeQuantization_2=a.asm.Ca).apply(null,arguments)},$b=a._emscripten_bind_ExpertEncoder_SetAttributeExplicitQuantization_5=function(){return($b=a._emscripten_bind_ExpertEncoder_SetAttributeExplicitQuantization_5=a.asm.Da).apply(null,arguments)},ac=a._emscripten_bind_ExpertEncoder_SetSpeedOptions_2=function(){return(ac=a._emscripten_bind_ExpertEncoder_SetSpeedOptions_2=
a.asm.Ea).apply(null,arguments)},bc=a._emscripten_bind_ExpertEncoder_SetTrackEncodedProperties_1=function(){return(bc=a._emscripten_bind_ExpertEncoder_SetTrackEncodedProperties_1=a.asm.Fa).apply(null,arguments)},cc=a._emscripten_bind_ExpertEncoder_EncodeToDracoBuffer_2=function(){return(cc=a._emscripten_bind_ExpertEncoder_EncodeToDracoBuffer_2=a.asm.Ga).apply(null,arguments)},dc=a._emscripten_bind_ExpertEncoder_GetNumberOfEncodedPoints_0=function(){return(dc=a._emscripten_bind_ExpertEncoder_GetNumberOfEncodedPoints_0=
a.asm.Ha).apply(null,arguments)},ec=a._emscripten_bind_ExpertEncoder_GetNumberOfEncodedFaces_0=function(){return(ec=a._emscripten_bind_ExpertEncoder_GetNumberOfEncodedFaces_0=a.asm.Ia).apply(null,arguments)},fc=a._emscripten_bind_ExpertEncoder___destroy___0=function(){return(fc=a._emscripten_bind_ExpertEncoder___destroy___0=a.asm.Ja).apply(null,arguments)},gc=a._emscripten_enum_draco_GeometryAttribute_Type_INVALID=function(){return(gc=a._emscripten_enum_draco_GeometryAttribute_Type_INVALID=a.asm.Ka).apply(null,
arguments)},hc=a._emscripten_enum_draco_GeometryAttribute_Type_POSITION=function(){return(hc=a._emscripten_enum_draco_GeometryAttribute_Type_POSITION=a.asm.La).apply(null,arguments)},ic=a._emscripten_enum_draco_GeometryAttribute_Type_NORMAL=function(){return(ic=a._emscripten_enum_draco_GeometryAttribute_Type_NORMAL=a.asm.Ma).apply(null,arguments)},jc=a._emscripten_enum_draco_GeometryAttribute_Type_COLOR=function(){return(jc=a._emscripten_enum_draco_GeometryAttribute_Type_COLOR=a.asm.Na).apply(null,
arguments)},kc=a._emscripten_enum_draco_GeometryAttribute_Type_TEX_COORD=function(){return(kc=a._emscripten_enum_draco_GeometryAttribute_Type_TEX_COORD=a.asm.Oa).apply(null,arguments)},lc=a._emscripten_enum_draco_GeometryAttribute_Type_GENERIC=function(){return(lc=a._emscripten_enum_draco_GeometryAttribute_Type_GENERIC=a.asm.Pa).apply(null,arguments)},mc=a._emscripten_enum_draco_EncodedGeometryType_INVALID_GEOMETRY_TYPE=function(){return(mc=a._emscripten_enum_draco_EncodedGeometryType_INVALID_GEOMETRY_TYPE=
a.asm.Qa).apply(null,arguments)},nc=a._emscripten_enum_draco_EncodedGeometryType_POINT_CLOUD=function(){return(nc=a._emscripten_enum_draco_EncodedGeometryType_POINT_CLOUD=a.asm.Ra).apply(null,arguments)},oc=a._emscripten_enum_draco_EncodedGeometryType_TRIANGULAR_MESH=function(){return(oc=a._emscripten_enum_draco_EncodedGeometryType_TRIANGULAR_MESH=a.asm.Sa).apply(null,arguments)},pc=a._emscripten_enum_draco_MeshEncoderMethod_MESH_SEQUENTIAL_ENCODING=function(){return(pc=a._emscripten_enum_draco_MeshEncoderMethod_MESH_SEQUENTIAL_ENCODING=
a.asm.Ta).apply(null,arguments)},qc=a._emscripten_enum_draco_MeshEncoderMethod_MESH_EDGEBREAKER_ENCODING=function(){return(qc=a._emscripten_enum_draco_MeshEncoderMethod_MESH_EDGEBREAKER_ENCODING=a.asm.Ua).apply(null,arguments)},Oa=a._malloc=function(){return(Oa=a._malloc=a.asm.Va).apply(null,arguments)};a._free=function(){return(a._free=a.asm.Wa).apply(null,arguments)};var fa;da=function b(){fa||T();fa||(da=b)};a.run=T;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();
T();w.prototype=Object.create(w.prototype);w.prototype.constructor=w;w.prototype.__class__=w;w.__cache__={};a.WrapperObject=w;a.getCache=D;a.wrapPointer=S;a.castObject=function(b,c){return S(b.ptr,c)};a.NULL=S(0);a.destroy=function(b){if(!b.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";b.__destroy__();delete D(b.__class__)[b.ptr]};a.compare=function(b,c){return b.ptr===c.ptr};a.getPointer=function(b){return b.ptr};a.getClass=function(b){return b.__class__};var n={buffer:0,
size:0,pos:0,temps:[],needed:0,prepare:function(){if(n.needed){for(var b=0;b<n.temps.length;b++)a._free(n.temps[b]);n.temps.length=0;a._free(n.buffer);n.buffer=0;n.size+=n.needed;n.needed=0}n.buffer||(n.size+=128,n.buffer=a._malloc(n.size),r(n.buffer));n.pos=0},alloc:function(b,c){r(n.buffer);b=b.length*c.BYTES_PER_ELEMENT;b=b+7&-8;n.pos+b>=n.size?(r(0<b),n.needed+=b,c=a._malloc(b),n.temps.push(c)):(c=n.buffer+n.pos,n.pos+=b);return c},copy:function(b,c,d){d>>>=0;switch(c.BYTES_PER_ELEMENT){case 2:d>>>=
1;break;case 4:d>>>=2;break;case 8:d>>>=3}for(var e=0;e<b.length;e++)c[d+e]=b[e]}};Q.prototype=Object.create(w.prototype);Q.prototype.constructor=Q;Q.prototype.__class__=Q;Q.__cache__={};a.VoidPtr=Q;Q.prototype.__destroy__=Q.prototype.__destroy__=function(){Pa(this.ptr)};M.prototype=Object.create(w.prototype);M.prototype.constructor=M;M.prototype.__class__=M;M.__cache__={};a.GeometryAttribute=M;M.prototype.__destroy__=M.prototype.__destroy__=function(){Qa(this.ptr)};z.prototype=Object.create(w.prototype);
z.prototype.constructor=z;z.prototype.__class__=z;z.__cache__={};a.PointAttribute=z;z.prototype.size=z.prototype.size=function(){return Ra(this.ptr)};z.prototype.attribute_type=z.prototype.attribute_type=function(){return Sa(this.ptr)};z.prototype.data_type=z.prototype.data_type=function(){return Ta(this.ptr)};z.prototype.num_components=z.prototype.num_components=function(){return Ua(this.ptr)};z.prototype.normalized=z.prototype.normalized=function(){return!!Va(this.ptr)};z.prototype.byte_stride=
z.prototype.byte_stride=function(){return Wa(this.ptr)};z.prototype.byte_offset=z.prototype.byte_offset=function(){return Xa(this.ptr)};z.prototype.unique_id=z.prototype.unique_id=function(){return Ya(this.ptr)};z.prototype.__destroy__=z.prototype.__destroy__=function(){Za(this.ptr)};G.prototype=Object.create(w.prototype);G.prototype.constructor=G;G.prototype.__class__=G;G.__cache__={};a.PointCloud=G;G.prototype.num_attributes=G.prototype.num_attributes=function(){return $a(this.ptr)};G.prototype.num_points=
G.prototype.num_points=function(){return ab(this.ptr)};G.prototype.__destroy__=G.prototype.__destroy__=function(){bb(this.ptr)};E.prototype=Object.create(w.prototype);E.prototype.constructor=E;E.prototype.__class__=E;E.__cache__={};a.Mesh=E;E.prototype.num_faces=E.prototype.num_faces=function(){return cb(this.ptr)};E.prototype.num_attributes=E.prototype.num_attributes=function(){return db(this.ptr)};E.prototype.num_points=E.prototype.num_points=function(){return eb(this.ptr)};E.prototype.set_num_points=
E.prototype.set_num_points=function(b){var c=this.ptr;b&&"object"===typeof b&&(b=b.ptr);fb(c,b)};E.prototype.__destroy__=E.prototype.__destroy__=function(){gb(this.ptr)};N.prototype=Object.create(w.prototype);N.prototype.constructor=N;N.prototype.__class__=N;N.__cache__={};a.Metadata=N;N.prototype.__destroy__=N.prototype.__destroy__=function(){hb(this.ptr)};H.prototype=Object.create(w.prototype);H.prototype.constructor=H;H.prototype.__class__=H;H.__cache__={};a.DracoInt8Array=H;H.prototype.GetValue=
H.prototype.GetValue=function(b){var c=this.ptr;b&&"object"===typeof b&&(b=b.ptr);return ib(c,b)};H.prototype.size=H.prototype.size=function(){return jb(this.ptr)};H.prototype.__destroy__=H.prototype.__destroy__=function(){kb(this.ptr)};F.prototype=Object.create(w.prototype);F.prototype.constructor=F;F.prototype.__class__=F;F.__cache__={};a.MetadataBuilder=F;F.prototype.AddStringEntry=F.prototype.AddStringEntry=function(b,c,d){var e=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c=c&&"object"===
typeof c?c.ptr:O(c);d=d&&"object"===typeof d?d.ptr:O(d);return!!lb(e,b,c,d)};F.prototype.AddIntEntry=F.prototype.AddIntEntry=function(b,c,d){var e=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c=c&&"object"===typeof c?c.ptr:O(c);d&&"object"===typeof d&&(d=d.ptr);return!!mb(e,b,c,d)};F.prototype.AddIntEntryArray=F.prototype.AddIntEntryArray=function(b,c,d,e){var g=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c=c&&"object"===typeof c?c.ptr:O(c);"object"==typeof d&&(d=V(d));e&&"object"===
typeof e&&(e=e.ptr);return!!nb(g,b,c,d,e)};F.prototype.AddDoubleEntry=F.prototype.AddDoubleEntry=function(b,c,d){var e=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c=c&&"object"===typeof c?c.ptr:O(c);d&&"object"===typeof d&&(d=d.ptr);return!!ob(e,b,c,d)};F.prototype.__destroy__=F.prototype.__destroy__=function(){pb(this.ptr)};x.prototype=Object.create(w.prototype);x.prototype.constructor=x;x.prototype.__class__=x;x.__cache__={};a.PointCloudBuilder=x;x.prototype.AddFloatAttribute=x.prototype.AddFloatAttribute=
function(b,c,d,e,g){var t=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);"object"==typeof g&&(g=ba(g));return qb(t,b,c,d,e,g)};x.prototype.AddInt8Attribute=x.prototype.AddInt8Attribute=function(b,c,d,e,g){var t=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);"object"==typeof g&&(g=
ha(g));return rb(t,b,c,d,e,g)};x.prototype.AddUInt8Attribute=x.prototype.AddUInt8Attribute=function(b,c,d,e,g){var t=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);"object"==typeof g&&(g=ha(g));return sb(t,b,c,d,e,g)};x.prototype.AddInt16Attribute=x.prototype.AddInt16Attribute=function(b,c,d,e,g){var t=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);
d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);"object"==typeof g&&(g=ia(g));return tb(t,b,c,d,e,g)};x.prototype.AddUInt16Attribute=x.prototype.AddUInt16Attribute=function(b,c,d,e,g){var t=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);"object"==typeof g&&(g=ia(g));return ub(t,b,c,d,e,g)};x.prototype.AddInt32Attribute=x.prototype.AddInt32Attribute=function(b,c,d,e,g){var t=
this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);"object"==typeof g&&(g=V(g));return vb(t,b,c,d,e,g)};x.prototype.AddUInt32Attribute=x.prototype.AddUInt32Attribute=function(b,c,d,e,g){var t=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);"object"==typeof g&&(g=V(g));return wb(t,b,c,d,
e,g)};x.prototype.AddMetadata=x.prototype.AddMetadata=function(b,c){var d=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);return!!xb(d,b,c)};x.prototype.SetMetadataForAttribute=x.prototype.SetMetadataForAttribute=function(b,c,d){var e=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!yb(e,b,c,d)};x.prototype.__destroy__=x.prototype.__destroy__=function(){zb(this.ptr)};u.prototype=Object.create(w.prototype);
u.prototype.constructor=u;u.prototype.__class__=u;u.__cache__={};a.MeshBuilder=u;u.prototype.AddFacesToMesh=u.prototype.AddFacesToMesh=function(b,c,d){var e=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);"object"==typeof d&&(d=V(d));return!!Ab(e,b,c,d)};u.prototype.AddFloatAttributeToMesh=u.prototype.AddFloatAttributeToMesh=function(b,c,d,e,g){var t=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&
(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);"object"==typeof g&&(g=ba(g));return Bb(t,b,c,d,e,g)};u.prototype.AddInt32AttributeToMesh=u.prototype.AddInt32AttributeToMesh=function(b,c,d,e,g){var t=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);"object"==typeof g&&(g=V(g));return Cb(t,b,c,d,e,g)};u.prototype.AddMetadataToMesh=u.prototype.AddMetadataToMesh=function(b,c){var d=this.ptr;b&&"object"===
typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);return!!Db(d,b,c)};u.prototype.AddFloatAttribute=u.prototype.AddFloatAttribute=function(b,c,d,e,g){var t=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);"object"==typeof g&&(g=ba(g));return Eb(t,b,c,d,e,g)};u.prototype.AddInt8Attribute=u.prototype.AddInt8Attribute=function(b,c,d,e,g){var t=this.ptr;n.prepare();b&&"object"===typeof b&&(b=
b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);"object"==typeof g&&(g=ha(g));return Fb(t,b,c,d,e,g)};u.prototype.AddUInt8Attribute=u.prototype.AddUInt8Attribute=function(b,c,d,e,g){var t=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);"object"==typeof g&&(g=ha(g));return Gb(t,b,c,d,e,g)};u.prototype.AddInt16Attribute=u.prototype.AddInt16Attribute=
function(b,c,d,e,g){var t=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);"object"==typeof g&&(g=ia(g));return Hb(t,b,c,d,e,g)};u.prototype.AddUInt16Attribute=u.prototype.AddUInt16Attribute=function(b,c,d,e,g){var t=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);"object"==typeof g&&
(g=ia(g));return Ib(t,b,c,d,e,g)};u.prototype.AddInt32Attribute=u.prototype.AddInt32Attribute=function(b,c,d,e,g){var t=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);"object"==typeof g&&(g=V(g));return Jb(t,b,c,d,e,g)};u.prototype.AddUInt32Attribute=u.prototype.AddUInt32Attribute=function(b,c,d,e,g){var t=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);
d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);"object"==typeof g&&(g=V(g));return Kb(t,b,c,d,e,g)};u.prototype.AddMetadata=u.prototype.AddMetadata=function(b,c){var d=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);return!!Lb(d,b,c)};u.prototype.SetMetadataForAttribute=u.prototype.SetMetadataForAttribute=function(b,c,d){var e=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!Mb(e,
b,c,d)};u.prototype.__destroy__=u.prototype.__destroy__=function(){Nb(this.ptr)};y.prototype=Object.create(w.prototype);y.prototype.constructor=y;y.prototype.__class__=y;y.__cache__={};a.Encoder=y;y.prototype.SetEncodingMethod=y.prototype.SetEncodingMethod=function(b){var c=this.ptr;b&&"object"===typeof b&&(b=b.ptr);Ob(c,b)};y.prototype.SetAttributeQuantization=y.prototype.SetAttributeQuantization=function(b,c){var d=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);Pb(d,
b,c)};y.prototype.SetAttributeExplicitQuantization=y.prototype.SetAttributeExplicitQuantization=function(b,c,d,e,g){var t=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);"object"==typeof e&&(e=ba(e));g&&"object"===typeof g&&(g=g.ptr);Qb(t,b,c,d,e,g)};y.prototype.SetSpeedOptions=y.prototype.SetSpeedOptions=function(b,c){var d=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);Rb(d,b,c)};y.prototype.SetTrackEncodedProperties=
y.prototype.SetTrackEncodedProperties=function(b){var c=this.ptr;b&&"object"===typeof b&&(b=b.ptr);Sb(c,b)};y.prototype.EncodeMeshToDracoBuffer=y.prototype.EncodeMeshToDracoBuffer=function(b,c){var d=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);return Tb(d,b,c)};y.prototype.EncodePointCloudToDracoBuffer=y.prototype.EncodePointCloudToDracoBuffer=function(b,c,d){var e=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&
(d=d.ptr);return Ub(e,b,c,d)};y.prototype.GetNumberOfEncodedPoints=y.prototype.GetNumberOfEncodedPoints=function(){return Vb(this.ptr)};y.prototype.GetNumberOfEncodedFaces=y.prototype.GetNumberOfEncodedFaces=function(){return Wb(this.ptr)};y.prototype.__destroy__=y.prototype.__destroy__=function(){Xb(this.ptr)};A.prototype=Object.create(w.prototype);A.prototype.constructor=A;A.prototype.__class__=A;A.__cache__={};a.ExpertEncoder=A;A.prototype.SetEncodingMethod=A.prototype.SetEncodingMethod=function(b){var c=
this.ptr;b&&"object"===typeof b&&(b=b.ptr);Yb(c,b)};A.prototype.SetAttributeQuantization=A.prototype.SetAttributeQuantization=function(b,c){var d=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);Zb(d,b,c)};A.prototype.SetAttributeExplicitQuantization=A.prototype.SetAttributeExplicitQuantization=function(b,c,d,e,g){var t=this.ptr;n.prepare();b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);"object"==typeof e&&(e=ba(e));
g&&"object"===typeof g&&(g=g.ptr);$b(t,b,c,d,e,g)};A.prototype.SetSpeedOptions=A.prototype.SetSpeedOptions=function(b,c){var d=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);ac(d,b,c)};A.prototype.SetTrackEncodedProperties=A.prototype.SetTrackEncodedProperties=function(b){var c=this.ptr;b&&"object"===typeof b&&(b=b.ptr);bc(c,b)};A.prototype.EncodeToDracoBuffer=A.prototype.EncodeToDracoBuffer=function(b,c){var d=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===
typeof c&&(c=c.ptr);return cc(d,b,c)};A.prototype.GetNumberOfEncodedPoints=A.prototype.GetNumberOfEncodedPoints=function(){return dc(this.ptr)};A.prototype.GetNumberOfEncodedFaces=A.prototype.GetNumberOfEncodedFaces=function(){return ec(this.ptr)};A.prototype.__destroy__=A.prototype.__destroy__=function(){fc(this.ptr)};(function(){function b(){a.INVALID=gc();a.POSITION=hc();a.NORMAL=ic();a.COLOR=jc();a.TEX_COORD=kc();a.GENERIC=lc();a.INVALID_GEOMETRY_TYPE=mc();a.POINT_CLOUD=nc();a.TRIANGULAR_MESH=
oc();a.MESH_SEQUENTIAL_ENCODING=pc();a.MESH_EDGEBREAKER_ENCODING=qc()}wa?b():qa.unshift(b)})();if("function"===typeof a.onModuleParsed)a.onModuleParsed();return p.ready}}();"object"===typeof exports&&"object"===typeof module?module.exports=DracoEncoderModule:"function"===typeof define&&define.amd?define([],function(){return DracoEncoderModule}):"object"===typeof exports&&(exports.DracoEncoderModule=DracoEncoderModule);
