var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(h){var n=0;return function(){return n<h.length?{done:!1,value:h[n++]}:{done:!0}}};$jscomp.arrayIterator=function(h){return{next:$jscomp.arrayIteratorImpl(h)}};$jscomp.makeIterator=function(h){var n="undefined"!=typeof Symbol&&Symbol.iterator&&h[Symbol.iterator];return n?n.call(h):$jscomp.arrayIterator(h)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.getGlobal=function(h){h=["object"==typeof globalThis&&globalThis,h,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var n=0;n<h.length;++n){var k=h[n];if(k&&k.Math==Math)return k}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(h,n,k){if(h==Array.prototype||h==Object.prototype)return h;h[n]=k.value;return h};$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";
var $jscomp$lookupPolyfilledValue=function(h,n){var k=$jscomp.propertyToPolyfillSymbol[n];if(null==k)return h[n];k=h[k];return void 0!==k?k:h[n]};$jscomp.polyfill=function(h,n,k,p){n&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(h,n,k,p):$jscomp.polyfillUnisolated(h,n,k,p))};
$jscomp.polyfillUnisolated=function(h,n,k,p){k=$jscomp.global;h=h.split(".");for(p=0;p<h.length-1;p++){var l=h[p];if(!(l in k))return;k=k[l]}h=h[h.length-1];p=k[h];n=n(p);n!=p&&null!=n&&$jscomp.defineProperty(k,h,{configurable:!0,writable:!0,value:n})};
$jscomp.polyfillIsolated=function(h,n,k,p){var l=h.split(".");h=1===l.length;p=l[0];p=!h&&p in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var y=0;y<l.length-1;y++){var f=l[y];if(!(f in p))return;p=p[f]}l=l[l.length-1];k=$jscomp.IS_SYMBOL_NATIVE&&"es6"===k?p[l]:null;n=n(k);null!=n&&(h?$jscomp.defineProperty($jscomp.polyfills,l,{configurable:!0,writable:!0,value:n}):n!==k&&(void 0===$jscomp.propertyToPolyfillSymbol[l]&&(k=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[l]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(l):$jscomp.POLYFILL_PREFIX+k+"$"+l),$jscomp.defineProperty(p,$jscomp.propertyToPolyfillSymbol[l],{configurable:!0,writable:!0,value:n})))};
$jscomp.polyfill("Promise",function(h){function n(){this.batch_=null}function k(f){return f instanceof l?f:new l(function(q,v){q(f)})}if(h&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return h;n.prototype.asyncExecute=function(f){if(null==this.batch_){this.batch_=[];var q=this;this.asyncExecuteFunction(function(){q.executeBatch_()})}this.batch_.push(f)};
var p=$jscomp.global.setTimeout;n.prototype.asyncExecuteFunction=function(f){p(f,0)};n.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var f=this.batch_;this.batch_=[];for(var q=0;q<f.length;++q){var v=f[q];f[q]=null;try{v()}catch(A){this.asyncThrow_(A)}}}this.batch_=null};n.prototype.asyncThrow_=function(f){this.asyncExecuteFunction(function(){throw f;})};var l=function(f){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var q=this.createResolveAndReject_();
try{f(q.resolve,q.reject)}catch(v){q.reject(v)}};l.prototype.createResolveAndReject_=function(){function f(A){return function(O){v||(v=!0,A.call(q,O))}}var q=this,v=!1;return{resolve:f(this.resolveTo_),reject:f(this.reject_)}};l.prototype.resolveTo_=function(f){if(f===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof l)this.settleSameAsPromise_(f);else{a:switch(typeof f){case "object":var q=null!=f;break a;case "function":q=!0;break a;default:q=!1}q?this.resolveToNonPromiseObj_(f):
this.fulfill_(f)}};l.prototype.resolveToNonPromiseObj_=function(f){var q=void 0;try{q=f.then}catch(v){this.reject_(v);return}"function"==typeof q?this.settleSameAsThenable_(q,f):this.fulfill_(f)};l.prototype.reject_=function(f){this.settle_(2,f)};l.prototype.fulfill_=function(f){this.settle_(1,f)};l.prototype.settle_=function(f,q){if(0!=this.state_)throw Error("Cannot settle("+f+", "+q+"): Promise already settled in state"+this.state_);this.state_=f;this.result_=q;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};l.prototype.scheduleUnhandledRejectionCheck_=function(){var f=this;p(function(){if(f.notifyUnhandledRejection_()){var q=$jscomp.global.console;"undefined"!==typeof q&&q.error(f.result_)}},1)};l.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var f=$jscomp.global.CustomEvent,q=$jscomp.global.Event,v=$jscomp.global.dispatchEvent;if("undefined"===typeof v)return!0;"function"===typeof f?f=new f("unhandledrejection",{cancelable:!0}):
"function"===typeof q?f=new q("unhandledrejection",{cancelable:!0}):(f=$jscomp.global.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.result_;return v(f)};l.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var f=0;f<this.onSettledCallbacks_.length;++f)y.asyncExecute(this.onSettledCallbacks_[f]);this.onSettledCallbacks_=null}};var y=new n;l.prototype.settleSameAsPromise_=function(f){var q=this.createResolveAndReject_();
f.callWhenSettled_(q.resolve,q.reject)};l.prototype.settleSameAsThenable_=function(f,q){var v=this.createResolveAndReject_();try{f.call(q,v.resolve,v.reject)}catch(A){v.reject(A)}};l.prototype.then=function(f,q){function v(t,x){return"function"==typeof t?function(D){try{A(t(D))}catch(R){O(R)}}:x}var A,O,Z=new l(function(t,x){A=t;O=x});this.callWhenSettled_(v(f,A),v(q,O));return Z};l.prototype.catch=function(f){return this.then(void 0,f)};l.prototype.callWhenSettled_=function(f,q){function v(){switch(A.state_){case 1:f(A.result_);
break;case 2:q(A.result_);break;default:throw Error("Unexpected state: "+A.state_);}}var A=this;null==this.onSettledCallbacks_?y.asyncExecute(v):this.onSettledCallbacks_.push(v);this.isRejectionHandled_=!0};l.resolve=k;l.reject=function(f){return new l(function(q,v){v(f)})};l.race=function(f){return new l(function(q,v){for(var A=$jscomp.makeIterator(f),O=A.next();!O.done;O=A.next())k(O.value).callWhenSettled_(q,v)})};l.all=function(f){var q=$jscomp.makeIterator(f),v=q.next();return v.done?k([]):new l(function(A,
O){function Z(D){return function(R){t[D]=R;x--;0==x&&A(t)}}var t=[],x=0;do t.push(void 0),x++,k(v.value).callWhenSettled_(Z(t.length-1),O),v=q.next();while(!v.done)})};return l},"es6","es3");$jscomp.owns=function(h,n){return Object.prototype.hasOwnProperty.call(h,n)};$jscomp.assign=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.assign?Object.assign:function(h,n){for(var k=1;k<arguments.length;k++){var p=arguments[k];if(p)for(var l in p)$jscomp.owns(p,l)&&(h[l]=p[l])}return h};
$jscomp.polyfill("Object.assign",function(h){return h||$jscomp.assign},"es6","es3");$jscomp.checkStringArgs=function(h,n,k){if(null==h)throw new TypeError("The 'this' value for String.prototype."+k+" must not be null or undefined");if(n instanceof RegExp)throw new TypeError("First argument to String.prototype."+k+" must not be a regular expression");return h+""};
$jscomp.polyfill("String.prototype.startsWith",function(h){return h?h:function(n,k){var p=$jscomp.checkStringArgs(this,n,"startsWith");n+="";var l=p.length,y=n.length;k=Math.max(0,Math.min(k|0,p.length));for(var f=0;f<y&&k<l;)if(p[k++]!=n[f++])return!1;return f>=y}},"es6","es3");
$jscomp.polyfill("Array.prototype.copyWithin",function(h){function n(k){k=Number(k);return Infinity===k||-Infinity===k?k:k|0}return h?h:function(k,p,l){var y=this.length;k=n(k);p=n(p);l=void 0===l?y:n(l);k=0>k?Math.max(y+k,0):Math.min(k,y);p=0>p?Math.max(y+p,0):Math.min(p,y);l=0>l?Math.max(y+l,0):Math.min(l,y);if(k<p)for(;p<l;)p in this?this[k++]=this[p++]:(delete this[k++],p++);else for(l=Math.min(l,y+p-k),k+=l-p;l>p;)--l in this?this[--k]=this[l]:delete this[--k];return this}},"es6","es3");
$jscomp.typedArrayCopyWithin=function(h){return h?h:Array.prototype.copyWithin};$jscomp.polyfill("Int8Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Uint8Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Uint8ClampedArray.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Int16Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");
$jscomp.polyfill("Uint16Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Int32Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Uint32Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Float32Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Float64Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");
var DracoDecoderModule=function(){var h="undefined"!==typeof document&&document.currentScript?document.currentScript.src:void 0;"undefined"!==typeof __filename&&(h=h||__filename);return function(n){function k(e){return a.locateFile?a.locateFile(e,U):U+e}function p(e,b){if(e){var c=ia;var d=e+b;for(b=e;c[b]&&!(b>=d);)++b;if(16<b-e&&c.buffer&&ua)c=ua.decode(c.subarray(e,b));else{for(d="";e<b;){var g=c[e++];if(g&128){var u=c[e++]&63;if(192==(g&224))d+=String.fromCharCode((g&31)<<6|u);else{var aa=c[e++]&
63;g=224==(g&240)?(g&15)<<12|u<<6|aa:(g&7)<<18|u<<12|aa<<6|c[e++]&63;65536>g?d+=String.fromCharCode(g):(g-=65536,d+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else d+=String.fromCharCode(g)}c=d}}else c="";return c}function l(e){va=e;a.HEAP8=W=new Int8Array(e);a.HEAP16=new Int16Array(e);a.HEAP32=ca=new Int32Array(e);a.HEAPU8=ia=new Uint8Array(e);a.HEAPU16=new Uint16Array(e);a.HEAPU32=Y=new Uint32Array(e);a.HEAPF32=new Float32Array(e);a.HEAPF64=new Float64Array(e)}function y(e){if(a.onAbort)a.onAbort(e);
e="Aborted("+e+")";da(e);wa=!0;e=new WebAssembly.RuntimeError(e+". Build with -sASSERTIONS for more info.");na(e);throw e;}function f(e){try{if(e==P&&ea)return new Uint8Array(ea);if(oa)return oa(e);throw"both async and sync fetching of the wasm failed";}catch(b){y(b)}}function q(){if(!ea&&(xa||fa)){if("function"==typeof fetch&&!P.startsWith("file://"))return fetch(P,{credentials:"same-origin"}).then(function(e){if(!e.ok)throw"failed to load wasm binary file at '"+P+"'";return e.arrayBuffer()}).catch(function(){return f(P)});
if(pa)return new Promise(function(e,b){pa(P,function(c){e(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return f(P)})}function v(e){for(;0<e.length;){var b=e.shift();if("function"==typeof b)b(a);else{var c=b.func;"number"==typeof c?void 0===b.arg?A(c)():A(c)(b.arg):c(void 0===b.arg?null:b.arg)}}}function A(e){var b=ja[e];b||(e>=ja.length&&(ja.length=e+1),ja[e]=b=ya.get(e));return b}function O(e){this.excPtr=e;this.ptr=e-24;this.set_type=function(b){Y[this.ptr+4>>2]=b};this.get_type=
function(){return Y[this.ptr+4>>2]};this.set_destructor=function(b){Y[this.ptr+8>>2]=b};this.get_destructor=function(){return Y[this.ptr+8>>2]};this.set_refcount=function(b){ca[this.ptr>>2]=b};this.set_caught=function(b){W[this.ptr+12>>0]=b?1:0};this.get_caught=function(){return 0!=W[this.ptr+12>>0]};this.set_rethrown=function(b){W[this.ptr+13>>0]=b?1:0};this.get_rethrown=function(){return 0!=W[this.ptr+13>>0]};this.init=function(b,c){this.set_adjusted_ptr(0);this.set_type(b);this.set_destructor(c);
this.set_refcount(0);this.set_caught(!1);this.set_rethrown(!1)};this.add_ref=function(){ca[this.ptr>>2]+=1};this.release_ref=function(){var b=ca[this.ptr>>2];ca[this.ptr>>2]=b-1;return 1===b};this.set_adjusted_ptr=function(b){Y[this.ptr+16>>2]=b};this.get_adjusted_ptr=function(){return Y[this.ptr+16>>2]};this.get_exception_ptr=function(){if(za(this.get_type()))return Y[this.excPtr>>2];var b=this.get_adjusted_ptr();return 0!==b?b:this.excPtr}}function Z(e){function b(){if(!ka&&(ka=!0,a.calledRun=!0,
!wa)){Aa=!0;v(qa);Ba(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;)Ca.unshift(a.postRun.shift());v(Ca)}}if(!(0<ba)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)Da.unshift(a.preRun.shift());v(Da);0<ba||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}function t(){}function x(e){return(e||t).__cache__}
function D(e,b){var c=x(b),d=c[e];if(d)return d;d=Object.create((b||t).prototype);d.ptr=e;return c[e]=d}function R(e){if("string"===typeof e){for(var b=0,c=0;c<e.length;++c){var d=e.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|e.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}b=Array(b+1);c=0;d=b.length;if(0<d){d=c+d-1;for(var g=0;g<e.length;++g){var u=e.charCodeAt(g);if(55296<=u&&57343>=u){var aa=e.charCodeAt(++g);u=65536+((u&1023)<<10)|aa&1023}if(127>=u){if(c>=d)break;
b[c++]=u}else{if(2047>=u){if(c+1>=d)break;b[c++]=192|u>>6}else{if(65535>=u){if(c+2>=d)break;b[c++]=224|u>>12}else{if(c+3>=d)break;b[c++]=240|u>>18;b[c++]=128|u>>12&63}b[c++]=128|u>>6&63}b[c++]=128|u&63}}b[c]=0}e=r.alloc(b,W);r.copy(b,W,e);return e}return e}function ra(e){if("object"===typeof e){var b=r.alloc(e,W);r.copy(e,W,b);return b}return e}function X(){throw"cannot construct a VoidPtr, no constructor in IDL";}function S(){this.ptr=Ea();x(S)[this.ptr]=this}function Q(){this.ptr=Fa();x(Q)[this.ptr]=
this}function V(){this.ptr=Ga();x(V)[this.ptr]=this}function w(){this.ptr=Ha();x(w)[this.ptr]=this}function C(){this.ptr=Ia();x(C)[this.ptr]=this}function F(){this.ptr=Ja();x(F)[this.ptr]=this}function G(){this.ptr=Ka();x(G)[this.ptr]=this}function E(){this.ptr=La();x(E)[this.ptr]=this}function T(){this.ptr=Ma();x(T)[this.ptr]=this}function B(){throw"cannot construct a Status, no constructor in IDL";}function H(){this.ptr=Na();x(H)[this.ptr]=this}function I(){this.ptr=Oa();x(I)[this.ptr]=this}function J(){this.ptr=
Pa();x(J)[this.ptr]=this}function K(){this.ptr=Qa();x(K)[this.ptr]=this}function L(){this.ptr=Ra();x(L)[this.ptr]=this}function M(){this.ptr=Sa();x(M)[this.ptr]=this}function N(){this.ptr=Ta();x(N)[this.ptr]=this}function z(){this.ptr=Ua();x(z)[this.ptr]=this}function m(){this.ptr=Va();x(m)[this.ptr]=this}n=n||{};var a="undefined"!=typeof n?n:{},Ba,na;a.ready=new Promise(function(e,b){Ba=e;na=b});var Wa=!1,Xa=!1;a.onRuntimeInitialized=function(){Wa=!0;if(Xa&&"function"===typeof a.onModuleLoaded)a.onModuleLoaded(a)};
a.onModuleParsed=function(){Xa=!0;if(Wa&&"function"===typeof a.onModuleLoaded)a.onModuleLoaded(a)};a.isVersionSupported=function(e){if("string"!==typeof e)return!1;e=e.split(".");return 2>e.length||3<e.length?!1:1==e[0]&&0<=e[1]&&5>=e[1]?!0:0!=e[0]||10<e[1]?!1:!0};var Ya=Object.assign({},a),xa="object"==typeof window,fa="function"==typeof importScripts,Za="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,U="",sa,la;if(Za){U=fa?require("path").dirname(U)+
"/":__dirname+"/";var $a=function(){la||(sa=require("fs"),la=require("path"))};var ab=function(e,b){$a();e=la.normalize(e);return sa.readFileSync(e,b?void 0:"utf8")};var oa=function(e){e=ab(e,!0);e.buffer||(e=new Uint8Array(e));return e};var pa=function(e,b,c){$a();e=la.normalize(e);sa.readFile(e,function(d,g){d?c(d):b(g.buffer)})};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);a.inspect=function(){return"[Emscripten Module object]"}}else if(xa||fa)fa?U=self.location.href:
"undefined"!=typeof document&&document.currentScript&&(U=document.currentScript.src),h&&(U=h),U=0!==U.indexOf("blob:")?U.substr(0,U.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ab=function(e){var b=new XMLHttpRequest;b.open("GET",e,!1);b.send(null);return b.responseText},fa&&(oa=function(e){var b=new XMLHttpRequest;b.open("GET",e,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),pa=function(e,b,c){var d=new XMLHttpRequest;d.open("GET",e,!0);d.responseType="arraybuffer";
d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};a.print||console.log.bind(console);var da=a.printErr||console.warn.bind(console);Object.assign(a,Ya);Ya=null;var ea;a.wasmBinary&&(ea=a.wasmBinary);"object"!=typeof WebAssembly&&y("no native wasm support detected");var ma,wa=!1,ua="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,va,W,ia,ca,Y,ya,Da=[],qa=[],Ca=[],Aa=!1,ba=0,ta=null,ha=null;var P="draco_decoder_gltf.wasm";P.startsWith("data:application/octet-stream;base64,")||
(P=k(P));var ja=[],vd=0,wd={c:function(e){return bb(e+24)+24},b:function(e,b,c){(new O(e)).init(b,c);vd++;throw e;},a:function(){y("")},e:function(e,b,c){ia.copyWithin(e,b,b+c)},d:function(e){var b=ia.length;e>>>=0;if(2147483648<e)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,e+100663296);var g=Math;d=Math.max(e,d);g=g.min.call(g,2147483648,d+(65536-d%65536)%65536);a:{try{ma.grow(g-va.byteLength+65535>>>16);l(ma.buffer);var u=1;break a}catch(aa){}u=void 0}if(u)return!0}return!1}};
(function(){function e(g,u){a.asm=g.exports;ma=a.asm.f;l(ma.buffer);ya=a.asm.h;qa.unshift(a.asm.g);ba--;a.monitorRunDependencies&&a.monitorRunDependencies(ba);0==ba&&(null!==ta&&(clearInterval(ta),ta=null),ha&&(g=ha,ha=null,g()))}function b(g){e(g.instance)}function c(g){return q().then(function(u){return WebAssembly.instantiate(u,d)}).then(function(u){return u}).then(g,function(u){da("failed to asynchronously prepare wasm: "+u);y(u)})}var d={a:wd};ba++;a.monitorRunDependencies&&a.monitorRunDependencies(ba);
if(a.instantiateWasm)try{return a.instantiateWasm(d,e)}catch(g){return da("Module.instantiateWasm callback failed with error: "+g),!1}(function(){return ea||"function"!=typeof WebAssembly.instantiateStreaming||P.startsWith("data:application/octet-stream;base64,")||P.startsWith("file://")||Za||"function"!=typeof fetch?c(b):fetch(P,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,d).then(b,function(u){da("wasm streaming compile failed: "+u);da("falling back to ArrayBuffer instantiation");
return c(b)})})})().catch(na);return{}})();a.___wasm_call_ctors=function(){return(a.___wasm_call_ctors=a.asm.g).apply(null,arguments)};var cb=a._emscripten_bind_VoidPtr___destroy___0=function(){return(cb=a._emscripten_bind_VoidPtr___destroy___0=a.asm.i).apply(null,arguments)},Ea=a._emscripten_bind_DecoderBuffer_DecoderBuffer_0=function(){return(Ea=a._emscripten_bind_DecoderBuffer_DecoderBuffer_0=a.asm.j).apply(null,arguments)},db=a._emscripten_bind_DecoderBuffer_Init_2=function(){return(db=a._emscripten_bind_DecoderBuffer_Init_2=
a.asm.k).apply(null,arguments)},eb=a._emscripten_bind_DecoderBuffer___destroy___0=function(){return(eb=a._emscripten_bind_DecoderBuffer___destroy___0=a.asm.l).apply(null,arguments)},Fa=a._emscripten_bind_AttributeTransformData_AttributeTransformData_0=function(){return(Fa=a._emscripten_bind_AttributeTransformData_AttributeTransformData_0=a.asm.m).apply(null,arguments)},fb=a._emscripten_bind_AttributeTransformData_transform_type_0=function(){return(fb=a._emscripten_bind_AttributeTransformData_transform_type_0=
a.asm.n).apply(null,arguments)},gb=a._emscripten_bind_AttributeTransformData___destroy___0=function(){return(gb=a._emscripten_bind_AttributeTransformData___destroy___0=a.asm.o).apply(null,arguments)},Ga=a._emscripten_bind_GeometryAttribute_GeometryAttribute_0=function(){return(Ga=a._emscripten_bind_GeometryAttribute_GeometryAttribute_0=a.asm.p).apply(null,arguments)},hb=a._emscripten_bind_GeometryAttribute___destroy___0=function(){return(hb=a._emscripten_bind_GeometryAttribute___destroy___0=a.asm.q).apply(null,
arguments)},Ha=a._emscripten_bind_PointAttribute_PointAttribute_0=function(){return(Ha=a._emscripten_bind_PointAttribute_PointAttribute_0=a.asm.r).apply(null,arguments)},ib=a._emscripten_bind_PointAttribute_size_0=function(){return(ib=a._emscripten_bind_PointAttribute_size_0=a.asm.s).apply(null,arguments)},jb=a._emscripten_bind_PointAttribute_GetAttributeTransformData_0=function(){return(jb=a._emscripten_bind_PointAttribute_GetAttributeTransformData_0=a.asm.t).apply(null,arguments)},kb=a._emscripten_bind_PointAttribute_attribute_type_0=
function(){return(kb=a._emscripten_bind_PointAttribute_attribute_type_0=a.asm.u).apply(null,arguments)},lb=a._emscripten_bind_PointAttribute_data_type_0=function(){return(lb=a._emscripten_bind_PointAttribute_data_type_0=a.asm.v).apply(null,arguments)},mb=a._emscripten_bind_PointAttribute_num_components_0=function(){return(mb=a._emscripten_bind_PointAttribute_num_components_0=a.asm.w).apply(null,arguments)},nb=a._emscripten_bind_PointAttribute_normalized_0=function(){return(nb=a._emscripten_bind_PointAttribute_normalized_0=
a.asm.x).apply(null,arguments)},ob=a._emscripten_bind_PointAttribute_byte_stride_0=function(){return(ob=a._emscripten_bind_PointAttribute_byte_stride_0=a.asm.y).apply(null,arguments)},pb=a._emscripten_bind_PointAttribute_byte_offset_0=function(){return(pb=a._emscripten_bind_PointAttribute_byte_offset_0=a.asm.z).apply(null,arguments)},qb=a._emscripten_bind_PointAttribute_unique_id_0=function(){return(qb=a._emscripten_bind_PointAttribute_unique_id_0=a.asm.A).apply(null,arguments)},rb=a._emscripten_bind_PointAttribute___destroy___0=
function(){return(rb=a._emscripten_bind_PointAttribute___destroy___0=a.asm.B).apply(null,arguments)},Ia=a._emscripten_bind_AttributeQuantizationTransform_AttributeQuantizationTransform_0=function(){return(Ia=a._emscripten_bind_AttributeQuantizationTransform_AttributeQuantizationTransform_0=a.asm.C).apply(null,arguments)},sb=a._emscripten_bind_AttributeQuantizationTransform_InitFromAttribute_1=function(){return(sb=a._emscripten_bind_AttributeQuantizationTransform_InitFromAttribute_1=a.asm.D).apply(null,
arguments)},tb=a._emscripten_bind_AttributeQuantizationTransform_quantization_bits_0=function(){return(tb=a._emscripten_bind_AttributeQuantizationTransform_quantization_bits_0=a.asm.E).apply(null,arguments)},ub=a._emscripten_bind_AttributeQuantizationTransform_min_value_1=function(){return(ub=a._emscripten_bind_AttributeQuantizationTransform_min_value_1=a.asm.F).apply(null,arguments)},vb=a._emscripten_bind_AttributeQuantizationTransform_range_0=function(){return(vb=a._emscripten_bind_AttributeQuantizationTransform_range_0=
a.asm.G).apply(null,arguments)},wb=a._emscripten_bind_AttributeQuantizationTransform___destroy___0=function(){return(wb=a._emscripten_bind_AttributeQuantizationTransform___destroy___0=a.asm.H).apply(null,arguments)},Ja=a._emscripten_bind_AttributeOctahedronTransform_AttributeOctahedronTransform_0=function(){return(Ja=a._emscripten_bind_AttributeOctahedronTransform_AttributeOctahedronTransform_0=a.asm.I).apply(null,arguments)},xb=a._emscripten_bind_AttributeOctahedronTransform_InitFromAttribute_1=
function(){return(xb=a._emscripten_bind_AttributeOctahedronTransform_InitFromAttribute_1=a.asm.J).apply(null,arguments)},yb=a._emscripten_bind_AttributeOctahedronTransform_quantization_bits_0=function(){return(yb=a._emscripten_bind_AttributeOctahedronTransform_quantization_bits_0=a.asm.K).apply(null,arguments)},zb=a._emscripten_bind_AttributeOctahedronTransform___destroy___0=function(){return(zb=a._emscripten_bind_AttributeOctahedronTransform___destroy___0=a.asm.L).apply(null,arguments)},Ka=a._emscripten_bind_PointCloud_PointCloud_0=
function(){return(Ka=a._emscripten_bind_PointCloud_PointCloud_0=a.asm.M).apply(null,arguments)},Ab=a._emscripten_bind_PointCloud_num_attributes_0=function(){return(Ab=a._emscripten_bind_PointCloud_num_attributes_0=a.asm.N).apply(null,arguments)},Bb=a._emscripten_bind_PointCloud_num_points_0=function(){return(Bb=a._emscripten_bind_PointCloud_num_points_0=a.asm.O).apply(null,arguments)},Cb=a._emscripten_bind_PointCloud___destroy___0=function(){return(Cb=a._emscripten_bind_PointCloud___destroy___0=a.asm.P).apply(null,
arguments)},La=a._emscripten_bind_Mesh_Mesh_0=function(){return(La=a._emscripten_bind_Mesh_Mesh_0=a.asm.Q).apply(null,arguments)},Db=a._emscripten_bind_Mesh_num_faces_0=function(){return(Db=a._emscripten_bind_Mesh_num_faces_0=a.asm.R).apply(null,arguments)},Eb=a._emscripten_bind_Mesh_num_attributes_0=function(){return(Eb=a._emscripten_bind_Mesh_num_attributes_0=a.asm.S).apply(null,arguments)},Fb=a._emscripten_bind_Mesh_num_points_0=function(){return(Fb=a._emscripten_bind_Mesh_num_points_0=a.asm.T).apply(null,
arguments)},Gb=a._emscripten_bind_Mesh___destroy___0=function(){return(Gb=a._emscripten_bind_Mesh___destroy___0=a.asm.U).apply(null,arguments)},Ma=a._emscripten_bind_Metadata_Metadata_0=function(){return(Ma=a._emscripten_bind_Metadata_Metadata_0=a.asm.V).apply(null,arguments)},Hb=a._emscripten_bind_Metadata___destroy___0=function(){return(Hb=a._emscripten_bind_Metadata___destroy___0=a.asm.W).apply(null,arguments)},Ib=a._emscripten_bind_Status_code_0=function(){return(Ib=a._emscripten_bind_Status_code_0=
a.asm.X).apply(null,arguments)},Jb=a._emscripten_bind_Status_ok_0=function(){return(Jb=a._emscripten_bind_Status_ok_0=a.asm.Y).apply(null,arguments)},Kb=a._emscripten_bind_Status_error_msg_0=function(){return(Kb=a._emscripten_bind_Status_error_msg_0=a.asm.Z).apply(null,arguments)},Lb=a._emscripten_bind_Status___destroy___0=function(){return(Lb=a._emscripten_bind_Status___destroy___0=a.asm._).apply(null,arguments)},Na=a._emscripten_bind_DracoFloat32Array_DracoFloat32Array_0=function(){return(Na=a._emscripten_bind_DracoFloat32Array_DracoFloat32Array_0=
a.asm.$).apply(null,arguments)},Mb=a._emscripten_bind_DracoFloat32Array_GetValue_1=function(){return(Mb=a._emscripten_bind_DracoFloat32Array_GetValue_1=a.asm.aa).apply(null,arguments)},Nb=a._emscripten_bind_DracoFloat32Array_size_0=function(){return(Nb=a._emscripten_bind_DracoFloat32Array_size_0=a.asm.ba).apply(null,arguments)},Ob=a._emscripten_bind_DracoFloat32Array___destroy___0=function(){return(Ob=a._emscripten_bind_DracoFloat32Array___destroy___0=a.asm.ca).apply(null,arguments)},Oa=a._emscripten_bind_DracoInt8Array_DracoInt8Array_0=
function(){return(Oa=a._emscripten_bind_DracoInt8Array_DracoInt8Array_0=a.asm.da).apply(null,arguments)},Pb=a._emscripten_bind_DracoInt8Array_GetValue_1=function(){return(Pb=a._emscripten_bind_DracoInt8Array_GetValue_1=a.asm.ea).apply(null,arguments)},Qb=a._emscripten_bind_DracoInt8Array_size_0=function(){return(Qb=a._emscripten_bind_DracoInt8Array_size_0=a.asm.fa).apply(null,arguments)},Rb=a._emscripten_bind_DracoInt8Array___destroy___0=function(){return(Rb=a._emscripten_bind_DracoInt8Array___destroy___0=
a.asm.ga).apply(null,arguments)},Pa=a._emscripten_bind_DracoUInt8Array_DracoUInt8Array_0=function(){return(Pa=a._emscripten_bind_DracoUInt8Array_DracoUInt8Array_0=a.asm.ha).apply(null,arguments)},Sb=a._emscripten_bind_DracoUInt8Array_GetValue_1=function(){return(Sb=a._emscripten_bind_DracoUInt8Array_GetValue_1=a.asm.ia).apply(null,arguments)},Tb=a._emscripten_bind_DracoUInt8Array_size_0=function(){return(Tb=a._emscripten_bind_DracoUInt8Array_size_0=a.asm.ja).apply(null,arguments)},Ub=a._emscripten_bind_DracoUInt8Array___destroy___0=
function(){return(Ub=a._emscripten_bind_DracoUInt8Array___destroy___0=a.asm.ka).apply(null,arguments)},Qa=a._emscripten_bind_DracoInt16Array_DracoInt16Array_0=function(){return(Qa=a._emscripten_bind_DracoInt16Array_DracoInt16Array_0=a.asm.la).apply(null,arguments)},Vb=a._emscripten_bind_DracoInt16Array_GetValue_1=function(){return(Vb=a._emscripten_bind_DracoInt16Array_GetValue_1=a.asm.ma).apply(null,arguments)},Wb=a._emscripten_bind_DracoInt16Array_size_0=function(){return(Wb=a._emscripten_bind_DracoInt16Array_size_0=
a.asm.na).apply(null,arguments)},Xb=a._emscripten_bind_DracoInt16Array___destroy___0=function(){return(Xb=a._emscripten_bind_DracoInt16Array___destroy___0=a.asm.oa).apply(null,arguments)},Ra=a._emscripten_bind_DracoUInt16Array_DracoUInt16Array_0=function(){return(Ra=a._emscripten_bind_DracoUInt16Array_DracoUInt16Array_0=a.asm.pa).apply(null,arguments)},Yb=a._emscripten_bind_DracoUInt16Array_GetValue_1=function(){return(Yb=a._emscripten_bind_DracoUInt16Array_GetValue_1=a.asm.qa).apply(null,arguments)},
Zb=a._emscripten_bind_DracoUInt16Array_size_0=function(){return(Zb=a._emscripten_bind_DracoUInt16Array_size_0=a.asm.ra).apply(null,arguments)},$b=a._emscripten_bind_DracoUInt16Array___destroy___0=function(){return($b=a._emscripten_bind_DracoUInt16Array___destroy___0=a.asm.sa).apply(null,arguments)},Sa=a._emscripten_bind_DracoInt32Array_DracoInt32Array_0=function(){return(Sa=a._emscripten_bind_DracoInt32Array_DracoInt32Array_0=a.asm.ta).apply(null,arguments)},ac=a._emscripten_bind_DracoInt32Array_GetValue_1=
function(){return(ac=a._emscripten_bind_DracoInt32Array_GetValue_1=a.asm.ua).apply(null,arguments)},bc=a._emscripten_bind_DracoInt32Array_size_0=function(){return(bc=a._emscripten_bind_DracoInt32Array_size_0=a.asm.va).apply(null,arguments)},cc=a._emscripten_bind_DracoInt32Array___destroy___0=function(){return(cc=a._emscripten_bind_DracoInt32Array___destroy___0=a.asm.wa).apply(null,arguments)},Ta=a._emscripten_bind_DracoUInt32Array_DracoUInt32Array_0=function(){return(Ta=a._emscripten_bind_DracoUInt32Array_DracoUInt32Array_0=
a.asm.xa).apply(null,arguments)},dc=a._emscripten_bind_DracoUInt32Array_GetValue_1=function(){return(dc=a._emscripten_bind_DracoUInt32Array_GetValue_1=a.asm.ya).apply(null,arguments)},ec=a._emscripten_bind_DracoUInt32Array_size_0=function(){return(ec=a._emscripten_bind_DracoUInt32Array_size_0=a.asm.za).apply(null,arguments)},fc=a._emscripten_bind_DracoUInt32Array___destroy___0=function(){return(fc=a._emscripten_bind_DracoUInt32Array___destroy___0=a.asm.Aa).apply(null,arguments)},Ua=a._emscripten_bind_MetadataQuerier_MetadataQuerier_0=
function(){return(Ua=a._emscripten_bind_MetadataQuerier_MetadataQuerier_0=a.asm.Ba).apply(null,arguments)},gc=a._emscripten_bind_MetadataQuerier_HasEntry_2=function(){return(gc=a._emscripten_bind_MetadataQuerier_HasEntry_2=a.asm.Ca).apply(null,arguments)},hc=a._emscripten_bind_MetadataQuerier_GetIntEntry_2=function(){return(hc=a._emscripten_bind_MetadataQuerier_GetIntEntry_2=a.asm.Da).apply(null,arguments)},ic=a._emscripten_bind_MetadataQuerier_GetIntEntryArray_3=function(){return(ic=a._emscripten_bind_MetadataQuerier_GetIntEntryArray_3=
a.asm.Ea).apply(null,arguments)},jc=a._emscripten_bind_MetadataQuerier_GetDoubleEntry_2=function(){return(jc=a._emscripten_bind_MetadataQuerier_GetDoubleEntry_2=a.asm.Fa).apply(null,arguments)},kc=a._emscripten_bind_MetadataQuerier_GetStringEntry_2=function(){return(kc=a._emscripten_bind_MetadataQuerier_GetStringEntry_2=a.asm.Ga).apply(null,arguments)},lc=a._emscripten_bind_MetadataQuerier_NumEntries_1=function(){return(lc=a._emscripten_bind_MetadataQuerier_NumEntries_1=a.asm.Ha).apply(null,arguments)},
mc=a._emscripten_bind_MetadataQuerier_GetEntryName_2=function(){return(mc=a._emscripten_bind_MetadataQuerier_GetEntryName_2=a.asm.Ia).apply(null,arguments)},nc=a._emscripten_bind_MetadataQuerier___destroy___0=function(){return(nc=a._emscripten_bind_MetadataQuerier___destroy___0=a.asm.Ja).apply(null,arguments)},Va=a._emscripten_bind_Decoder_Decoder_0=function(){return(Va=a._emscripten_bind_Decoder_Decoder_0=a.asm.Ka).apply(null,arguments)},oc=a._emscripten_bind_Decoder_DecodeArrayToPointCloud_3=function(){return(oc=
a._emscripten_bind_Decoder_DecodeArrayToPointCloud_3=a.asm.La).apply(null,arguments)},pc=a._emscripten_bind_Decoder_DecodeArrayToMesh_3=function(){return(pc=a._emscripten_bind_Decoder_DecodeArrayToMesh_3=a.asm.Ma).apply(null,arguments)},qc=a._emscripten_bind_Decoder_GetAttributeId_2=function(){return(qc=a._emscripten_bind_Decoder_GetAttributeId_2=a.asm.Na).apply(null,arguments)},rc=a._emscripten_bind_Decoder_GetAttributeIdByName_2=function(){return(rc=a._emscripten_bind_Decoder_GetAttributeIdByName_2=
a.asm.Oa).apply(null,arguments)},sc=a._emscripten_bind_Decoder_GetAttributeIdByMetadataEntry_3=function(){return(sc=a._emscripten_bind_Decoder_GetAttributeIdByMetadataEntry_3=a.asm.Pa).apply(null,arguments)},tc=a._emscripten_bind_Decoder_GetAttribute_2=function(){return(tc=a._emscripten_bind_Decoder_GetAttribute_2=a.asm.Qa).apply(null,arguments)},uc=a._emscripten_bind_Decoder_GetAttributeByUniqueId_2=function(){return(uc=a._emscripten_bind_Decoder_GetAttributeByUniqueId_2=a.asm.Ra).apply(null,arguments)},
vc=a._emscripten_bind_Decoder_GetMetadata_1=function(){return(vc=a._emscripten_bind_Decoder_GetMetadata_1=a.asm.Sa).apply(null,arguments)},wc=a._emscripten_bind_Decoder_GetAttributeMetadata_2=function(){return(wc=a._emscripten_bind_Decoder_GetAttributeMetadata_2=a.asm.Ta).apply(null,arguments)},xc=a._emscripten_bind_Decoder_GetFaceFromMesh_3=function(){return(xc=a._emscripten_bind_Decoder_GetFaceFromMesh_3=a.asm.Ua).apply(null,arguments)},yc=a._emscripten_bind_Decoder_GetTriangleStripsFromMesh_2=
function(){return(yc=a._emscripten_bind_Decoder_GetTriangleStripsFromMesh_2=a.asm.Va).apply(null,arguments)},zc=a._emscripten_bind_Decoder_GetTrianglesUInt16Array_3=function(){return(zc=a._emscripten_bind_Decoder_GetTrianglesUInt16Array_3=a.asm.Wa).apply(null,arguments)},Ac=a._emscripten_bind_Decoder_GetTrianglesUInt32Array_3=function(){return(Ac=a._emscripten_bind_Decoder_GetTrianglesUInt32Array_3=a.asm.Xa).apply(null,arguments)},Bc=a._emscripten_bind_Decoder_GetAttributeFloat_3=function(){return(Bc=
a._emscripten_bind_Decoder_GetAttributeFloat_3=a.asm.Ya).apply(null,arguments)},Cc=a._emscripten_bind_Decoder_GetAttributeFloatForAllPoints_3=function(){return(Cc=a._emscripten_bind_Decoder_GetAttributeFloatForAllPoints_3=a.asm.Za).apply(null,arguments)},Dc=a._emscripten_bind_Decoder_GetAttributeIntForAllPoints_3=function(){return(Dc=a._emscripten_bind_Decoder_GetAttributeIntForAllPoints_3=a.asm._a).apply(null,arguments)},Ec=a._emscripten_bind_Decoder_GetAttributeInt8ForAllPoints_3=function(){return(Ec=
a._emscripten_bind_Decoder_GetAttributeInt8ForAllPoints_3=a.asm.$a).apply(null,arguments)},Fc=a._emscripten_bind_Decoder_GetAttributeUInt8ForAllPoints_3=function(){return(Fc=a._emscripten_bind_Decoder_GetAttributeUInt8ForAllPoints_3=a.asm.ab).apply(null,arguments)},Gc=a._emscripten_bind_Decoder_GetAttributeInt16ForAllPoints_3=function(){return(Gc=a._emscripten_bind_Decoder_GetAttributeInt16ForAllPoints_3=a.asm.bb).apply(null,arguments)},Hc=a._emscripten_bind_Decoder_GetAttributeUInt16ForAllPoints_3=
function(){return(Hc=a._emscripten_bind_Decoder_GetAttributeUInt16ForAllPoints_3=a.asm.cb).apply(null,arguments)},Ic=a._emscripten_bind_Decoder_GetAttributeInt32ForAllPoints_3=function(){return(Ic=a._emscripten_bind_Decoder_GetAttributeInt32ForAllPoints_3=a.asm.db).apply(null,arguments)},Jc=a._emscripten_bind_Decoder_GetAttributeUInt32ForAllPoints_3=function(){return(Jc=a._emscripten_bind_Decoder_GetAttributeUInt32ForAllPoints_3=a.asm.eb).apply(null,arguments)},Kc=a._emscripten_bind_Decoder_GetAttributeDataArrayForAllPoints_5=
function(){return(Kc=a._emscripten_bind_Decoder_GetAttributeDataArrayForAllPoints_5=a.asm.fb).apply(null,arguments)},Lc=a._emscripten_bind_Decoder_SkipAttributeTransform_1=function(){return(Lc=a._emscripten_bind_Decoder_SkipAttributeTransform_1=a.asm.gb).apply(null,arguments)},Mc=a._emscripten_bind_Decoder_GetEncodedGeometryType_Deprecated_1=function(){return(Mc=a._emscripten_bind_Decoder_GetEncodedGeometryType_Deprecated_1=a.asm.hb).apply(null,arguments)},Nc=a._emscripten_bind_Decoder_DecodeBufferToPointCloud_2=
function(){return(Nc=a._emscripten_bind_Decoder_DecodeBufferToPointCloud_2=a.asm.ib).apply(null,arguments)},Oc=a._emscripten_bind_Decoder_DecodeBufferToMesh_2=function(){return(Oc=a._emscripten_bind_Decoder_DecodeBufferToMesh_2=a.asm.jb).apply(null,arguments)},Pc=a._emscripten_bind_Decoder___destroy___0=function(){return(Pc=a._emscripten_bind_Decoder___destroy___0=a.asm.kb).apply(null,arguments)},Qc=a._emscripten_enum_draco_AttributeTransformType_ATTRIBUTE_INVALID_TRANSFORM=function(){return(Qc=a._emscripten_enum_draco_AttributeTransformType_ATTRIBUTE_INVALID_TRANSFORM=
a.asm.lb).apply(null,arguments)},Rc=a._emscripten_enum_draco_AttributeTransformType_ATTRIBUTE_NO_TRANSFORM=function(){return(Rc=a._emscripten_enum_draco_AttributeTransformType_ATTRIBUTE_NO_TRANSFORM=a.asm.mb).apply(null,arguments)},Sc=a._emscripten_enum_draco_AttributeTransformType_ATTRIBUTE_QUANTIZATION_TRANSFORM=function(){return(Sc=a._emscripten_enum_draco_AttributeTransformType_ATTRIBUTE_QUANTIZATION_TRANSFORM=a.asm.nb).apply(null,arguments)},Tc=a._emscripten_enum_draco_AttributeTransformType_ATTRIBUTE_OCTAHEDRON_TRANSFORM=
function(){return(Tc=a._emscripten_enum_draco_AttributeTransformType_ATTRIBUTE_OCTAHEDRON_TRANSFORM=a.asm.ob).apply(null,arguments)},Uc=a._emscripten_enum_draco_GeometryAttribute_Type_INVALID=function(){return(Uc=a._emscripten_enum_draco_GeometryAttribute_Type_INVALID=a.asm.pb).apply(null,arguments)},Vc=a._emscripten_enum_draco_GeometryAttribute_Type_POSITION=function(){return(Vc=a._emscripten_enum_draco_GeometryAttribute_Type_POSITION=a.asm.qb).apply(null,arguments)},Wc=a._emscripten_enum_draco_GeometryAttribute_Type_NORMAL=
function(){return(Wc=a._emscripten_enum_draco_GeometryAttribute_Type_NORMAL=a.asm.rb).apply(null,arguments)},Xc=a._emscripten_enum_draco_GeometryAttribute_Type_COLOR=function(){return(Xc=a._emscripten_enum_draco_GeometryAttribute_Type_COLOR=a.asm.sb).apply(null,arguments)},Yc=a._emscripten_enum_draco_GeometryAttribute_Type_TEX_COORD=function(){return(Yc=a._emscripten_enum_draco_GeometryAttribute_Type_TEX_COORD=a.asm.tb).apply(null,arguments)},Zc=a._emscripten_enum_draco_GeometryAttribute_Type_GENERIC=
function(){return(Zc=a._emscripten_enum_draco_GeometryAttribute_Type_GENERIC=a.asm.ub).apply(null,arguments)},$c=a._emscripten_enum_draco_EncodedGeometryType_INVALID_GEOMETRY_TYPE=function(){return($c=a._emscripten_enum_draco_EncodedGeometryType_INVALID_GEOMETRY_TYPE=a.asm.vb).apply(null,arguments)},ad=a._emscripten_enum_draco_EncodedGeometryType_POINT_CLOUD=function(){return(ad=a._emscripten_enum_draco_EncodedGeometryType_POINT_CLOUD=a.asm.wb).apply(null,arguments)},bd=a._emscripten_enum_draco_EncodedGeometryType_TRIANGULAR_MESH=
function(){return(bd=a._emscripten_enum_draco_EncodedGeometryType_TRIANGULAR_MESH=a.asm.xb).apply(null,arguments)},cd=a._emscripten_enum_draco_DataType_DT_INVALID=function(){return(cd=a._emscripten_enum_draco_DataType_DT_INVALID=a.asm.yb).apply(null,arguments)},dd=a._emscripten_enum_draco_DataType_DT_INT8=function(){return(dd=a._emscripten_enum_draco_DataType_DT_INT8=a.asm.zb).apply(null,arguments)},ed=a._emscripten_enum_draco_DataType_DT_UINT8=function(){return(ed=a._emscripten_enum_draco_DataType_DT_UINT8=
a.asm.Ab).apply(null,arguments)},fd=a._emscripten_enum_draco_DataType_DT_INT16=function(){return(fd=a._emscripten_enum_draco_DataType_DT_INT16=a.asm.Bb).apply(null,arguments)},gd=a._emscripten_enum_draco_DataType_DT_UINT16=function(){return(gd=a._emscripten_enum_draco_DataType_DT_UINT16=a.asm.Cb).apply(null,arguments)},hd=a._emscripten_enum_draco_DataType_DT_INT32=function(){return(hd=a._emscripten_enum_draco_DataType_DT_INT32=a.asm.Db).apply(null,arguments)},id=a._emscripten_enum_draco_DataType_DT_UINT32=
function(){return(id=a._emscripten_enum_draco_DataType_DT_UINT32=a.asm.Eb).apply(null,arguments)},jd=a._emscripten_enum_draco_DataType_DT_INT64=function(){return(jd=a._emscripten_enum_draco_DataType_DT_INT64=a.asm.Fb).apply(null,arguments)},kd=a._emscripten_enum_draco_DataType_DT_UINT64=function(){return(kd=a._emscripten_enum_draco_DataType_DT_UINT64=a.asm.Gb).apply(null,arguments)},ld=a._emscripten_enum_draco_DataType_DT_FLOAT32=function(){return(ld=a._emscripten_enum_draco_DataType_DT_FLOAT32=a.asm.Hb).apply(null,
arguments)},md=a._emscripten_enum_draco_DataType_DT_FLOAT64=function(){return(md=a._emscripten_enum_draco_DataType_DT_FLOAT64=a.asm.Ib).apply(null,arguments)},nd=a._emscripten_enum_draco_DataType_DT_BOOL=function(){return(nd=a._emscripten_enum_draco_DataType_DT_BOOL=a.asm.Jb).apply(null,arguments)},od=a._emscripten_enum_draco_DataType_DT_TYPES_COUNT=function(){return(od=a._emscripten_enum_draco_DataType_DT_TYPES_COUNT=a.asm.Kb).apply(null,arguments)},pd=a._emscripten_enum_draco_StatusCode_OK=function(){return(pd=
a._emscripten_enum_draco_StatusCode_OK=a.asm.Lb).apply(null,arguments)},qd=a._emscripten_enum_draco_StatusCode_DRACO_ERROR=function(){return(qd=a._emscripten_enum_draco_StatusCode_DRACO_ERROR=a.asm.Mb).apply(null,arguments)},rd=a._emscripten_enum_draco_StatusCode_IO_ERROR=function(){return(rd=a._emscripten_enum_draco_StatusCode_IO_ERROR=a.asm.Nb).apply(null,arguments)},sd=a._emscripten_enum_draco_StatusCode_INVALID_PARAMETER=function(){return(sd=a._emscripten_enum_draco_StatusCode_INVALID_PARAMETER=
a.asm.Ob).apply(null,arguments)},td=a._emscripten_enum_draco_StatusCode_UNSUPPORTED_VERSION=function(){return(td=a._emscripten_enum_draco_StatusCode_UNSUPPORTED_VERSION=a.asm.Pb).apply(null,arguments)},ud=a._emscripten_enum_draco_StatusCode_UNKNOWN_VERSION=function(){return(ud=a._emscripten_enum_draco_StatusCode_UNKNOWN_VERSION=a.asm.Qb).apply(null,arguments)},bb=a._malloc=function(){return(bb=a._malloc=a.asm.Rb).apply(null,arguments)};a._free=function(){return(a._free=a.asm.Sb).apply(null,arguments)};
var za=a.___cxa_is_pointer_type=function(){return(za=a.___cxa_is_pointer_type=a.asm.Tb).apply(null,arguments)},ka;ha=function b(){ka||Z();ka||(ha=b)};a.run=Z;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();Z();t.prototype=Object.create(t.prototype);t.prototype.constructor=t;t.prototype.__class__=t;t.__cache__={};a.WrapperObject=t;a.getCache=x;a.wrapPointer=D;a.castObject=function(b,c){return D(b.ptr,c)};a.NULL=D(0);a.destroy=function(b){if(!b.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";
b.__destroy__();delete x(b.__class__)[b.ptr]};a.compare=function(b,c){return b.ptr===c.ptr};a.getPointer=function(b){return b.ptr};a.getClass=function(b){return b.__class__};var r={buffer:0,size:0,pos:0,temps:[],needed:0,prepare:function(){if(r.needed){for(var b=0;b<r.temps.length;b++)a._free(r.temps[b]);r.temps.length=0;a._free(r.buffer);r.buffer=0;r.size+=r.needed;r.needed=0}r.buffer||(r.size+=128,r.buffer=a._malloc(r.size),r.buffer||y(void 0));r.pos=0},alloc:function(b,c){r.buffer||y(void 0);b=
b.length*c.BYTES_PER_ELEMENT;b=b+7&-8;r.pos+b>=r.size?(0<b||y(void 0),r.needed+=b,c=a._malloc(b),r.temps.push(c)):(c=r.buffer+r.pos,r.pos+=b);return c},copy:function(b,c,d){d>>>=0;switch(c.BYTES_PER_ELEMENT){case 2:d>>>=1;break;case 4:d>>>=2;break;case 8:d>>>=3}for(var g=0;g<b.length;g++)c[d+g]=b[g]}};X.prototype=Object.create(t.prototype);X.prototype.constructor=X;X.prototype.__class__=X;X.__cache__={};a.VoidPtr=X;X.prototype.__destroy__=X.prototype.__destroy__=function(){cb(this.ptr)};S.prototype=
Object.create(t.prototype);S.prototype.constructor=S;S.prototype.__class__=S;S.__cache__={};a.DecoderBuffer=S;S.prototype.Init=S.prototype.Init=function(b,c){var d=this.ptr;r.prepare();"object"==typeof b&&(b=ra(b));c&&"object"===typeof c&&(c=c.ptr);db(d,b,c)};S.prototype.__destroy__=S.prototype.__destroy__=function(){eb(this.ptr)};Q.prototype=Object.create(t.prototype);Q.prototype.constructor=Q;Q.prototype.__class__=Q;Q.__cache__={};a.AttributeTransformData=Q;Q.prototype.transform_type=Q.prototype.transform_type=
function(){return fb(this.ptr)};Q.prototype.__destroy__=Q.prototype.__destroy__=function(){gb(this.ptr)};V.prototype=Object.create(t.prototype);V.prototype.constructor=V;V.prototype.__class__=V;V.__cache__={};a.GeometryAttribute=V;V.prototype.__destroy__=V.prototype.__destroy__=function(){hb(this.ptr)};w.prototype=Object.create(t.prototype);w.prototype.constructor=w;w.prototype.__class__=w;w.__cache__={};a.PointAttribute=w;w.prototype.size=w.prototype.size=function(){return ib(this.ptr)};w.prototype.GetAttributeTransformData=
w.prototype.GetAttributeTransformData=function(){return D(jb(this.ptr),Q)};w.prototype.attribute_type=w.prototype.attribute_type=function(){return kb(this.ptr)};w.prototype.data_type=w.prototype.data_type=function(){return lb(this.ptr)};w.prototype.num_components=w.prototype.num_components=function(){return mb(this.ptr)};w.prototype.normalized=w.prototype.normalized=function(){return!!nb(this.ptr)};w.prototype.byte_stride=w.prototype.byte_stride=function(){return ob(this.ptr)};w.prototype.byte_offset=
w.prototype.byte_offset=function(){return pb(this.ptr)};w.prototype.unique_id=w.prototype.unique_id=function(){return qb(this.ptr)};w.prototype.__destroy__=w.prototype.__destroy__=function(){rb(this.ptr)};C.prototype=Object.create(t.prototype);C.prototype.constructor=C;C.prototype.__class__=C;C.__cache__={};a.AttributeQuantizationTransform=C;C.prototype.InitFromAttribute=C.prototype.InitFromAttribute=function(b){var c=this.ptr;b&&"object"===typeof b&&(b=b.ptr);return!!sb(c,b)};C.prototype.quantization_bits=
C.prototype.quantization_bits=function(){return tb(this.ptr)};C.prototype.min_value=C.prototype.min_value=function(b){var c=this.ptr;b&&"object"===typeof b&&(b=b.ptr);return ub(c,b)};C.prototype.range=C.prototype.range=function(){return vb(this.ptr)};C.prototype.__destroy__=C.prototype.__destroy__=function(){wb(this.ptr)};F.prototype=Object.create(t.prototype);F.prototype.constructor=F;F.prototype.__class__=F;F.__cache__={};a.AttributeOctahedronTransform=F;F.prototype.InitFromAttribute=F.prototype.InitFromAttribute=
function(b){var c=this.ptr;b&&"object"===typeof b&&(b=b.ptr);return!!xb(c,b)};F.prototype.quantization_bits=F.prototype.quantization_bits=function(){return yb(this.ptr)};F.prototype.__destroy__=F.prototype.__destroy__=function(){zb(this.ptr)};G.prototype=Object.create(t.prototype);G.prototype.constructor=G;G.prototype.__class__=G;G.__cache__={};a.PointCloud=G;G.prototype.num_attributes=G.prototype.num_attributes=function(){return Ab(this.ptr)};G.prototype.num_points=G.prototype.num_points=function(){return Bb(this.ptr)};
G.prototype.__destroy__=G.prototype.__destroy__=function(){Cb(this.ptr)};E.prototype=Object.create(t.prototype);E.prototype.constructor=E;E.prototype.__class__=E;E.__cache__={};a.Mesh=E;E.prototype.num_faces=E.prototype.num_faces=function(){return Db(this.ptr)};E.prototype.num_attributes=E.prototype.num_attributes=function(){return Eb(this.ptr)};E.prototype.num_points=E.prototype.num_points=function(){return Fb(this.ptr)};E.prototype.__destroy__=E.prototype.__destroy__=function(){Gb(this.ptr)};T.prototype=
Object.create(t.prototype);T.prototype.constructor=T;T.prototype.__class__=T;T.__cache__={};a.Metadata=T;T.prototype.__destroy__=T.prototype.__destroy__=function(){Hb(this.ptr)};B.prototype=Object.create(t.prototype);B.prototype.constructor=B;B.prototype.__class__=B;B.__cache__={};a.Status=B;B.prototype.code=B.prototype.code=function(){return Ib(this.ptr)};B.prototype.ok=B.prototype.ok=function(){return!!Jb(this.ptr)};B.prototype.error_msg=B.prototype.error_msg=function(){return p(Kb(this.ptr))};
B.prototype.__destroy__=B.prototype.__destroy__=function(){Lb(this.ptr)};H.prototype=Object.create(t.prototype);H.prototype.constructor=H;H.prototype.__class__=H;H.__cache__={};a.DracoFloat32Array=H;H.prototype.GetValue=H.prototype.GetValue=function(b){var c=this.ptr;b&&"object"===typeof b&&(b=b.ptr);return Mb(c,b)};H.prototype.size=H.prototype.size=function(){return Nb(this.ptr)};H.prototype.__destroy__=H.prototype.__destroy__=function(){Ob(this.ptr)};I.prototype=Object.create(t.prototype);I.prototype.constructor=
I;I.prototype.__class__=I;I.__cache__={};a.DracoInt8Array=I;I.prototype.GetValue=I.prototype.GetValue=function(b){var c=this.ptr;b&&"object"===typeof b&&(b=b.ptr);return Pb(c,b)};I.prototype.size=I.prototype.size=function(){return Qb(this.ptr)};I.prototype.__destroy__=I.prototype.__destroy__=function(){Rb(this.ptr)};J.prototype=Object.create(t.prototype);J.prototype.constructor=J;J.prototype.__class__=J;J.__cache__={};a.DracoUInt8Array=J;J.prototype.GetValue=J.prototype.GetValue=function(b){var c=
this.ptr;b&&"object"===typeof b&&(b=b.ptr);return Sb(c,b)};J.prototype.size=J.prototype.size=function(){return Tb(this.ptr)};J.prototype.__destroy__=J.prototype.__destroy__=function(){Ub(this.ptr)};K.prototype=Object.create(t.prototype);K.prototype.constructor=K;K.prototype.__class__=K;K.__cache__={};a.DracoInt16Array=K;K.prototype.GetValue=K.prototype.GetValue=function(b){var c=this.ptr;b&&"object"===typeof b&&(b=b.ptr);return Vb(c,b)};K.prototype.size=K.prototype.size=function(){return Wb(this.ptr)};
K.prototype.__destroy__=K.prototype.__destroy__=function(){Xb(this.ptr)};L.prototype=Object.create(t.prototype);L.prototype.constructor=L;L.prototype.__class__=L;L.__cache__={};a.DracoUInt16Array=L;L.prototype.GetValue=L.prototype.GetValue=function(b){var c=this.ptr;b&&"object"===typeof b&&(b=b.ptr);return Yb(c,b)};L.prototype.size=L.prototype.size=function(){return Zb(this.ptr)};L.prototype.__destroy__=L.prototype.__destroy__=function(){$b(this.ptr)};M.prototype=Object.create(t.prototype);M.prototype.constructor=
M;M.prototype.__class__=M;M.__cache__={};a.DracoInt32Array=M;M.prototype.GetValue=M.prototype.GetValue=function(b){var c=this.ptr;b&&"object"===typeof b&&(b=b.ptr);return ac(c,b)};M.prototype.size=M.prototype.size=function(){return bc(this.ptr)};M.prototype.__destroy__=M.prototype.__destroy__=function(){cc(this.ptr)};N.prototype=Object.create(t.prototype);N.prototype.constructor=N;N.prototype.__class__=N;N.__cache__={};a.DracoUInt32Array=N;N.prototype.GetValue=N.prototype.GetValue=function(b){var c=
this.ptr;b&&"object"===typeof b&&(b=b.ptr);return dc(c,b)};N.prototype.size=N.prototype.size=function(){return ec(this.ptr)};N.prototype.__destroy__=N.prototype.__destroy__=function(){fc(this.ptr)};z.prototype=Object.create(t.prototype);z.prototype.constructor=z;z.prototype.__class__=z;z.__cache__={};a.MetadataQuerier=z;z.prototype.HasEntry=z.prototype.HasEntry=function(b,c){var d=this.ptr;r.prepare();b&&"object"===typeof b&&(b=b.ptr);c=c&&"object"===typeof c?c.ptr:R(c);return!!gc(d,b,c)};z.prototype.GetIntEntry=
z.prototype.GetIntEntry=function(b,c){var d=this.ptr;r.prepare();b&&"object"===typeof b&&(b=b.ptr);c=c&&"object"===typeof c?c.ptr:R(c);return hc(d,b,c)};z.prototype.GetIntEntryArray=z.prototype.GetIntEntryArray=function(b,c,d){var g=this.ptr;r.prepare();b&&"object"===typeof b&&(b=b.ptr);c=c&&"object"===typeof c?c.ptr:R(c);d&&"object"===typeof d&&(d=d.ptr);ic(g,b,c,d)};z.prototype.GetDoubleEntry=z.prototype.GetDoubleEntry=function(b,c){var d=this.ptr;r.prepare();b&&"object"===typeof b&&(b=b.ptr);c=
c&&"object"===typeof c?c.ptr:R(c);return jc(d,b,c)};z.prototype.GetStringEntry=z.prototype.GetStringEntry=function(b,c){var d=this.ptr;r.prepare();b&&"object"===typeof b&&(b=b.ptr);c=c&&"object"===typeof c?c.ptr:R(c);return p(kc(d,b,c))};z.prototype.NumEntries=z.prototype.NumEntries=function(b){var c=this.ptr;b&&"object"===typeof b&&(b=b.ptr);return lc(c,b)};z.prototype.GetEntryName=z.prototype.GetEntryName=function(b,c){var d=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=
c.ptr);return p(mc(d,b,c))};z.prototype.__destroy__=z.prototype.__destroy__=function(){nc(this.ptr)};m.prototype=Object.create(t.prototype);m.prototype.constructor=m;m.prototype.__class__=m;m.__cache__={};a.Decoder=m;m.prototype.DecodeArrayToPointCloud=m.prototype.DecodeArrayToPointCloud=function(b,c,d){var g=this.ptr;r.prepare();"object"==typeof b&&(b=ra(b));c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);return D(oc(g,b,c,d),B)};m.prototype.DecodeArrayToMesh=m.prototype.DecodeArrayToMesh=
function(b,c,d){var g=this.ptr;r.prepare();"object"==typeof b&&(b=ra(b));c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);return D(pc(g,b,c,d),B)};m.prototype.GetAttributeId=m.prototype.GetAttributeId=function(b,c){var d=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);return qc(d,b,c)};m.prototype.GetAttributeIdByName=m.prototype.GetAttributeIdByName=function(b,c){var d=this.ptr;r.prepare();b&&"object"===typeof b&&(b=b.ptr);c=c&&"object"===typeof c?
c.ptr:R(c);return rc(d,b,c)};m.prototype.GetAttributeIdByMetadataEntry=m.prototype.GetAttributeIdByMetadataEntry=function(b,c,d){var g=this.ptr;r.prepare();b&&"object"===typeof b&&(b=b.ptr);c=c&&"object"===typeof c?c.ptr:R(c);d=d&&"object"===typeof d?d.ptr:R(d);return sc(g,b,c,d)};m.prototype.GetAttribute=m.prototype.GetAttribute=function(b,c){var d=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);return D(tc(d,b,c),w)};m.prototype.GetAttributeByUniqueId=m.prototype.GetAttributeByUniqueId=
function(b,c){var d=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);return D(uc(d,b,c),w)};m.prototype.GetMetadata=m.prototype.GetMetadata=function(b){var c=this.ptr;b&&"object"===typeof b&&(b=b.ptr);return D(vc(c,b),T)};m.prototype.GetAttributeMetadata=m.prototype.GetAttributeMetadata=function(b,c){var d=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);return D(wc(d,b,c),T)};m.prototype.GetFaceFromMesh=m.prototype.GetFaceFromMesh=function(b,
c,d){var g=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!xc(g,b,c,d)};m.prototype.GetTriangleStripsFromMesh=m.prototype.GetTriangleStripsFromMesh=function(b,c){var d=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);return yc(d,b,c)};m.prototype.GetTrianglesUInt16Array=m.prototype.GetTrianglesUInt16Array=function(b,c,d){var g=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);
d&&"object"===typeof d&&(d=d.ptr);return!!zc(g,b,c,d)};m.prototype.GetTrianglesUInt32Array=m.prototype.GetTrianglesUInt32Array=function(b,c,d){var g=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!Ac(g,b,c,d)};m.prototype.GetAttributeFloat=m.prototype.GetAttributeFloat=function(b,c,d){var g=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!Bc(g,b,c,d)};m.prototype.GetAttributeFloatForAllPoints=
m.prototype.GetAttributeFloatForAllPoints=function(b,c,d){var g=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!Cc(g,b,c,d)};m.prototype.GetAttributeIntForAllPoints=m.prototype.GetAttributeIntForAllPoints=function(b,c,d){var g=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!Dc(g,b,c,d)};m.prototype.GetAttributeInt8ForAllPoints=m.prototype.GetAttributeInt8ForAllPoints=
function(b,c,d){var g=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!Ec(g,b,c,d)};m.prototype.GetAttributeUInt8ForAllPoints=m.prototype.GetAttributeUInt8ForAllPoints=function(b,c,d){var g=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!Fc(g,b,c,d)};m.prototype.GetAttributeInt16ForAllPoints=m.prototype.GetAttributeInt16ForAllPoints=function(b,c,d){var g=this.ptr;
b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!Gc(g,b,c,d)};m.prototype.GetAttributeUInt16ForAllPoints=m.prototype.GetAttributeUInt16ForAllPoints=function(b,c,d){var g=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!Hc(g,b,c,d)};m.prototype.GetAttributeInt32ForAllPoints=m.prototype.GetAttributeInt32ForAllPoints=function(b,c,d){var g=this.ptr;b&&"object"===typeof b&&
(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!Ic(g,b,c,d)};m.prototype.GetAttributeUInt32ForAllPoints=m.prototype.GetAttributeUInt32ForAllPoints=function(b,c,d){var g=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!Jc(g,b,c,d)};m.prototype.GetAttributeDataArrayForAllPoints=m.prototype.GetAttributeDataArrayForAllPoints=function(b,c,d,g,u){var aa=this.ptr;b&&"object"===typeof b&&(b=b.ptr);
c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);g&&"object"===typeof g&&(g=g.ptr);u&&"object"===typeof u&&(u=u.ptr);return!!Kc(aa,b,c,d,g,u)};m.prototype.SkipAttributeTransform=m.prototype.SkipAttributeTransform=function(b){var c=this.ptr;b&&"object"===typeof b&&(b=b.ptr);Lc(c,b)};m.prototype.GetEncodedGeometryType_Deprecated=m.prototype.GetEncodedGeometryType_Deprecated=function(b){var c=this.ptr;b&&"object"===typeof b&&(b=b.ptr);return Mc(c,b)};m.prototype.DecodeBufferToPointCloud=
m.prototype.DecodeBufferToPointCloud=function(b,c){var d=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);return D(Nc(d,b,c),B)};m.prototype.DecodeBufferToMesh=m.prototype.DecodeBufferToMesh=function(b,c){var d=this.ptr;b&&"object"===typeof b&&(b=b.ptr);c&&"object"===typeof c&&(c=c.ptr);return D(Oc(d,b,c),B)};m.prototype.__destroy__=m.prototype.__destroy__=function(){Pc(this.ptr)};(function(){function b(){a.ATTRIBUTE_INVALID_TRANSFORM=Qc();a.ATTRIBUTE_NO_TRANSFORM=Rc();
a.ATTRIBUTE_QUANTIZATION_TRANSFORM=Sc();a.ATTRIBUTE_OCTAHEDRON_TRANSFORM=Tc();a.INVALID=Uc();a.POSITION=Vc();a.NORMAL=Wc();a.COLOR=Xc();a.TEX_COORD=Yc();a.GENERIC=Zc();a.INVALID_GEOMETRY_TYPE=$c();a.POINT_CLOUD=ad();a.TRIANGULAR_MESH=bd();a.DT_INVALID=cd();a.DT_INT8=dd();a.DT_UINT8=ed();a.DT_INT16=fd();a.DT_UINT16=gd();a.DT_INT32=hd();a.DT_UINT32=id();a.DT_INT64=jd();a.DT_UINT64=kd();a.DT_FLOAT32=ld();a.DT_FLOAT64=md();a.DT_BOOL=nd();a.DT_TYPES_COUNT=od();a.OK=pd();a.DRACO_ERROR=qd();a.IO_ERROR=rd();
a.INVALID_PARAMETER=sd();a.UNSUPPORTED_VERSION=td();a.UNKNOWN_VERSION=ud()}Aa?b():qa.unshift(b)})();if("function"===typeof a.onModuleParsed)a.onModuleParsed();a.Decoder.prototype.GetEncodedGeometryType=function(b){if(b.__class__&&b.__class__===a.DecoderBuffer)return a.Decoder.prototype.GetEncodedGeometryType_Deprecated(b);if(8>b.byteLength)return a.INVALID_GEOMETRY_TYPE;switch(b[7]){case 0:return a.POINT_CLOUD;case 1:return a.TRIANGULAR_MESH;default:return a.INVALID_GEOMETRY_TYPE}};return n.ready}}();
"object"===typeof exports&&"object"===typeof module?module.exports=DracoDecoderModule:"function"===typeof define&&define.amd?define([],function(){return DracoDecoderModule}):"object"===typeof exports&&(exports.DracoDecoderModule=DracoDecoderModule);
