on: [pull_request]
name: draco-install-test
jobs:
  test:
    strategy:
      matrix:
        include:
          - test_name: ubuntu-latest-make
            os: ubuntu-latest
            test_command: python3 test.py -v -G "Unix Makefiles"

          - test_name: macos-latest-make
            os: macos-latest
            test_command: python3 test.py -v -G "Unix Makefiles"

          - test_name: macos-latest-xcode
            os: macos-latest
            test_command: python3 test.py -v -G Xcode

          - test_name: windows-latest-make
            os: windows-latest
            test_command: python3 test.py -v -G "MinGW Makefiles"

          - test_name: windows-latest-msvc
            os: windows-latest
            test_command: python3 test.py -v -G "Visual Studio 16 2019"

    name: ${{ matrix.test_name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone Draco with Submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run src/draco/tools/install_test/test.py
        shell: bash
        run: ${{ matrix.test_command }}
        working-directory: ./src/draco/tools/install_test
