on: [pull_request]
name: draco-presubmit
jobs:
  test:
    strategy:
      matrix:
        include:
          - test_name: macos-latest-make-clang-release-shared
            os: macos-latest
            cmake_configure_command: |-
              cmake .. -G "Unix Makefiles" \
                -DBUILD_SHARED_LIBS=ON \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=clang \
                -DCMAKE_CXX_COMPILER=clang++ \
                -DDRACO_TESTS=ON
            cmake_build_command: cmake --build . -- -j2
            draco_test_command: ./draco_tests

          - test_name: macos-latest-make-clang-release-static
            os: macos-latest
            cmake_configure_command: |-
              cmake .. -G "Unix Makefiles" \
                -DBUILD_SHARED_LIBS=OFF \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=clang \
                -DCMAKE_CXX_COMPILER=clang++ \
                -DDRACO_TESTS=ON
            cmake_build_command: cmake --build . -- -j2
            draco_test_command: ./draco_tests

          - test_name: macos-latest-xcode-release-shared
            os: macos-latest
            cmake_configure_command: |-
              cmake .. -G Xcode \
                -DBUILD_SHARED_LIBS=ON \
                -DCMAKE_CONFIGURATION_TYPES=Release \
                -DDRACO_TESTS=ON
            cmake_build_command: cmake --build .
            draco_test_command: Release/draco_tests

          - test_name: macos-latest-xcode-release-static
            os: macos-latest
            cmake_configure_command: |-
              cmake .. -G Xcode \
                -DBUILD_SHARED_LIBS=OFF \
                -DCMAKE_CONFIGURATION_TYPES=Release \
                -DDRACO_TESTS=ON
            cmake_build_command: cmake --build .
            draco_test_command: Release/draco_tests

          - test_name: ubuntu-latest-make-gcc10-release-shared
            os: ubuntu-latest
            cmake_configure_command: |-
              cmake .. -G "Unix Makefiles" \
                -DBUILD_SHARED_LIBS=ON \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=gcc-10 \
                -DCMAKE_CXX_COMPILER=g++-10 \
                -DDRACO_TESTS=ON
            cmake_build_command: cmake --build . -- -j2
            draco_test_command: ./draco_tests

          - test_name: ubuntu-latest-make-gcc10-release-static
            os: ubuntu-latest
            cmake_configure_command: |-
              cmake .. -G "Unix Makefiles" \
                -DBUILD_SHARED_LIBS=OFF \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=gcc-10 \
                -DCMAKE_CXX_COMPILER=g++-10 \
                -DDRACO_TESTS=ON
            cmake_build_command: cmake --build . -- -j2
            draco_test_command: ./draco_tests

          - test_name: windows-latest-msvc-release-shared
            os: windows-latest
            cmake_configure_command: |-
              cmake .. -G "Visual Studio 16 2019" \
                -DBUILD_SHARED_LIBS=ON \
                -DCMAKE_CONFIGURATION_TYPES=Release \
                -DDRACO_TESTS=ON
            cmake_build_command: cmake --build . -- -m:2
            draco_test_command: Release/draco_tests

    name: ${{ matrix.test_name }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create build directory.
        shell: bash
        run: mkdir _gh_build

      - name: Configure CMake build.
        shell: bash
        run: ${{ matrix.cmake_configure_command }}
        working-directory: ./_gh_build

      - name: Build with CMake.
        shell: bash
        run: ${{ matrix.cmake_build_command }}
        working-directory: ./_gh_build

      - name: Run tests.
        shell: bash
        run: ${{ matrix.draco_test_command }}
        working-directory: ./_gh_build
