// Copyright 2016 The Draco Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// This file is used by emscripten's WebIDL Binder.
// http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/WebIDL-Binder.html
#include "compression/decode.h"
#include "core/decoder_buffer.h"
#include "javascript/emscripten/webidl_wrapper.h"
#include "mesh/mesh.h"
#include "point_cloud/geometry_attribute.h"
#include "point_cloud/point_attribute.h"
#include "point_cloud/point_cloud.h"

// glue.cpp is generated by Makefile.emcc build_glue target.
#include "glue.cpp"
